### ISSUE TITLE
Please add type signatures to the examples.

### ISSUE THREAD

**Issue by joehillen** [elm-lang/elm-lang.org#109]
I spent some time trying to learn Elm this weekend, and I got stuck trying to understand what the types are supposed to be. For example, I still don't know what type `main` is expecting.

Could you please add type signatures to all of the examples, especially the complex examples like [Mario](http://elm-lang.org/edit/examples/Intermediate/Mario.elm).

Thank you.

**Comment by evancz** [comment]
Types are used a ton more in the examples. I tried to follow "best practice" style in pretty much all of them. Let's open PR's for specific examples if it can be improved.
