### ISSUE TITLE
Stack space overflow for simple code

### ISSUE THREAD

**Issue by danoctavian** [elm-lang/elm-lang.org#130]
The following code causes an overflow when run by using elm-server (v 0.11).

import Mouse
import WebSocket
import Window
import Keyboard

struct = {word = ""} 
update dir table =  {table | word = "wtf"} -- notice mistake here: '=' instead of '<-'
main = asText  <~ (foldp update struct Keyboard.arrows)

**Comment by evancz** [comment]
This is a variation of [this issue](https://github.com/elm-lang/elm-compiler/issues/832) so follow along there for the fix.

Thanks for the report!
