### ISSUE TITLE
Calculator Displays NaN when inputting Small Numbers

### ISSUE THREAD

**Issue by maxsnew** [elm-lang/elm-lang.org#149]
Repro: 
1. Go http://elm-lang.org/edit/examples/Intermediate/Calculator.elm
2. Press the `.` button.

It works if you press `0` then `.` though, so this could probably be fixed by just interpreting `.` as `0.` when there's no input.

**Comment by evancz** [comment]
This example is not part of the core examples anymore. I tried to rewrite it with elm-html but lost steam.
