### ISSUE TITLE
problem at cabal configure step

### ISSUE THREAD

**Issue by billyblackburn** [elm-lang/elm-lang.org#161]
[billy@localhost elm-lang.org]$ sudo cabal configure 
[sudo] password for billy: 
Resolving dependencies...
Configuring elm-website-0.1.0.2...
cabal: At least the following dependencies are missing:
Elm >=0.12,
aeson -any,
blaze-html -any,
blaze-markup -any,
cmdargs -any,
snap-core -any,
snap-server -any

i narrowed it down to aeson which I did a --force-install and it then screwed up the elm 0.12 install. 

everything else has worked as I am trying out the examples and what not.  anyone one else have this problem.  Im on Fedora 20 btw

**Comment by evancz** [comment]
I guess this won't be reproducible any more. Sorry to not give a satisfying answer here :/

I'll work on getting the build instructions nicer so this does not happen again.
