### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by danse** [elm-lang/elm-lang.org#162]
I was interested about the rationale behind Elm, but this link is broken, along with several others:

https://github.com/elm-lang/elm-lang.org/blob/master/public/learn/FAQ.elm#L17

**Comment by ifraixedes** [comment]
I've found a broken link in the following file and line
https://github.com/elm-lang/elm-lang.org/blob/master/frontend/public/Install.elm#L97

**Comment by evancz** [comment]
@ifraixedes, do you mind opening a PR? I recently renamed src/ to installers/

**Comment by ifraixedes** [comment]
I've sent it

**Comment by zapu** [comment]
There is another broken link in the FAQ, here:

https://github.com/elm-lang/elm-lang.org/blob/master/frontend/public/learn/FAQ.elm#L50

Unfortunately, it was also not archived by web.archive.org because of robots.txt.

**Comment by evancz** [comment]
It seems that everything at testblogpleaseignore has been lost :/ Sorry, but I don't think there is anything to be done here. I'll try to write up the modern form of those ideas at some point though!
