### ISSUE TITLE
build instructions with sandbox?

### ISSUE THREAD

**Issue by jvoigtlaender** [elm-lang/elm-lang.org#167]
If the Elm compiler package is going to be built using cabal sandbox, see here:

https://github.com/elm-lang/Elm/pull/726

then the build instructions for elm-lang.org seem to need refinement as well. Maybe making sure that the website is built inside a subdirectory of that sandbox, maybe with a symlink to .cabal-sandbox from the enclosing directory.

See mailing list thread:

https://groups.google.com/d/msg/elm-discuss/VK_N4LBToiw/5cDDaUVc4qQJ

**Comment by evancz** [comment]
Okay, time has passed such that a lot of the build scripts use sandboxes now and a lot more people actually have a reasonable time getting sandboxes working on their machine. So the current build instructions use sandboxes, which seems to resolve the root issue here.

I'll check out the arch instructions as well!
