### ISSUE TITLE
Shall we remove the "\"s in this introduction part?

### ISSUE THREAD

**Issue by eccstartup** [elm-lang/elm-lang.org#168]
https://github.com/elm-lang/elm-lang.org/blob/master/public/learn/courses/beginner/Graphics.elm#L126

https://github.com/elm-lang/elm-lang.org/blob/master/public/learn/courses/beginner/Graphics.elm#L142

**Comment by evancz** [comment]
This should be resolved by the move from [markdown| ... |] to elm-markdown
