### ISSUE TITLE
Input field is not compatible with special character input or non-English IME

### ISSUE THREAD

**Issue by bigdrum** [elm-lang/elm-lang.org#174]
Steps to reproduce:
1. Visit http://elm-lang.org/edit/examples/Reactive/TextField.elm with a Mac.
2. Type "abcd" in the field.
3. Move caret to between 'a' and 'b'.
4. Long press key 'e', the OSX will show a list to choose different diacritical mark.
5. choose 'è'.

Expected result:
The final text in the text field should be 'aèbcd'

Current result:
The final text is: 'aebèd'.

**Comment by evancz** [comment]
I moved this over to the elm-lang/core repo where the root of the bug is. Thanks for the report!

https://github.com/elm-lang/core/issues/272
