### ISSUE TITLE
Links to examples for Linear- and RadialGradient broken (404)

### ISSUE THREAD

**Issue by diomat** [elm-lang/elm-lang.org#175]
Hi,

the links for the Gradient examples on the [library](http://library.elm-lang.org/catalog/elm-lang-Elm/0.13/Color) page are broken (404). They link to http://**library**.elm-lang.org/edit/examples/Elements/LinearGradient.elm but should link to http://elm-lang.org/edit/examples/Elements/LinearGradient.elm and http://elm-lang.org/edit/examples/Elements/RadialGradient.elm, I guess?

Cheers

**Comment by evancz** [comment]
Thanks, and thanks for the PR!
