### ISSUE TITLE
A problem with hot-swapping

### ISSUE THREAD

**Issue by jvoigtlaender** [elm-lang/elm-lang.org#176]
Tried this code on http://elm-lang.org/try:
```haskell
import Graphics.Input (..)

hvr = input False

box = hoverable hvr.handle identity (collage 20 20 [outlined (solid black) (square 15)])

main = lift (\hvr -> flow down [asText hvr, box]) hvr.signal
```
Works, the Boolean changes when the mouse hovers in/out the square.

Now, live-changing one of the 20s to something else, say 15. One can see that hot-swapping gets applied, namely the square shape gets moved by a few pixels (due to the new collage dimensions). However, the Boolean will not anymore change on hover-in/hover-out over the square. So, did the connection between the `hoverable` element and the target `hvr.handle`/`hvr.signal` somehow get destroyed during the hot-swap?

**Comment by evancz** [comment]
Editor doesn't hot swap for now

**Comment by Ivanca** [comment]
No hot swapping, no time-traveling. You are making moving from HTML/JS to Elm less attractive as days go by (and by consequence, harder sell to any boss/IT)

**Comment by evancz** [comment]
Like I have said in other places, the `elm-reactor` features are coming back. I think it would have been a mistake for 0.17 to still not be out blocked on that. Hopefully that provides some context.
