### ISSUE TITLE
error when running run-elm-website

### ISSUE THREAD

**Issue by zartstrom** [elm-lang/elm-lang.org#181]
I followed the instructions and resulted with this:

[phil@arch elm-lang.org]$ ./dist/build/run-elm-website/run-elm-website
Initializing Server
.run-elm-website: elm: readProcessWithExitCode: runInteractiveProcess: exec: does not exist (No such file or directory)

What am I missing? Thanks in advance

**Comment by evancz** [comment]
Sorry for the trouble on this, and sorry for a slow / non-helpful reply.

I don't know how to reproduce this, and the website has been updated significantly today, so the same error should not be happening with the new stuff.

If you run into trouble with the new things, please report it and let us know: what OS you are using, what version of ghc and cabal you have, the particular commands you ran to get to this point. Lots of weird things can go wrong in the build process unfortunately :/
