### ISSUE TITLE
Ports Learn page is missing info on possibility of static ports 

### ISSUE THREAD

**Issue by Apanatshka** [elm-lang/elm-lang.org#182]
See also: https://groups.google.com/d/topic/elm-discuss/mkOD1YaBtjM/discussion

The confusion of the poster of that thread points out a weakness in the documentation of Ports:
The page only gives example code of ports which are of type `Signal x`.

Only when you look carefully at the examples that are linked to on page, do you see that "static" (non-`Signal` typed) Ports are also possible. And that they can be used for program start-up configuration (static in-ports) and exporting of functionality (static out-ports, main use is functions I think?). 

It would be nice to have that more prominently on the Learn page.

**Comment by trotha01** [comment]
It looks like there's a section at the bottom that specifies what can be sent through a port, under "Customs and Border Protection":
http://elm-lang.org/guide/interop

Maybe it was added after this issue was posted?

**Comment by evancz** [comment]
Not relevant with 0.17
