### ISSUE TITLE
Textured form performance issue

### ISSUE THREAD

**Issue by thSoft** [elm-lang/elm-lang.org#186]
With Elm 0.13, displaying a textured form consumes full CPU. You can reproduce this e.g with [this example](http://elm-lang.org/edit/examples/Elements/Texture.elm).

**Comment by etaque** [comment]
Hi,
Hitting this as well with Elm 0.14 on [Tacks](http://www.playtacks.com/). Here are Chrome CPU profiling screenshots:
 - with racing area as a filled rect:

![54a4979a120000300001ae3e 2015-01-18 18-58-56](https://cloud.githubusercontent.com/assets/40526/5793448/2a4f6778-9f44-11e4-858b-c70a09182a7f.png)

- with racing area as a textured rect (image being 200*200 jpeg file):

![54a4979a120000300001ae3e 2015-01-18 18-58-41](https://cloud.githubusercontent.com/assets/40526/5793449/2a524e3e-9f44-11e4-87c4-a1abf85b4078.png)

**Comment by evancz** [comment]
All stuff like this lives in `evancz/elm-graphics` now. Move over there if still an issue.
