### ISSUE TITLE
Elm.worker errors when created from within a web worker

### ISSUE THREAD

**Issue by mmport80** [elm-lang/elm-lang.org#187]
The error is:

"ReferenceError: document is not defined elm-runtime.js:2731"

from Elm 0.13; line 2731 is part of the function "htmlHeight(width, rawHtml)" function.

More comments on the issue can be read here:

https://groups.google.com/forum/#!topic/elm-discuss/hi4nNvHxFUA

**Comment by evancz** [comment]
Moved this over to elm-lang/core which is where the root bug is. Thanks for the report!

https://github.com/elm-lang/core/issues/273
