### ISSUE TITLE
Page content cut off on http://elm-lang.org/learn/Records.elm

### ISSUE THREAD

**Issue by jameshfisher** [elm-lang/elm-lang.org#198]
See bottom of screenshot: ![elm extensible records](https://cloud.githubusercontent.com/assets/166966/5428146/9309241c-83af-11e4-83e1-2a0899484401.png)

This behavior is the same on recent Chrome and Firefox.

**Comment by iamdoron** [comment]
I saw the same behavior in Safari (Version 8.0.3 (10600.3.14)) & Chrome (39.0.2171.95 (64-bit)) for Mac. 

It seems as if the div that contains most of the text height is 5215px instead of some higher value.

**Comment by thSoft** [comment]
This is also reproducible on other pages, e.g. http://elm-lang.org/Examples.elm.

**Comment by evancz** [comment]
I have seen this as well, can someone try to debug this issue?

**Comment by evancz** [comment]
Finally resolved by the website redo. Thanks for reporting!
