### ISSUE TITLE
Document comparable/appendable/number typing rules

### ISSUE THREAD

**Issue by jameshfisher** [elm-lang/elm-lang.org#199]
The only information I can see on this `comparable` thing comes from the compiler itself when it complains:

```
Looks like you want something comparable, but the only valid comparable
types are Int, Float, Char, String, lists, or tuples.
```

However this doesn't really explain the typing rules etc. I think this would be worth documenting, since it seems like an unusual language feature (at least to me, from a Haskell background).

Does it work like a primitive, hard-coded typeclass? `(<)` has type `comparable -> comparable -> Bool`, which in my mind says that e.g. `3 < "foo"` is type-correct, although it isn't. I guess all instances of `comparable` in a type signature must be instantiated to the same type? This seems overly restrictive because there's no way to write a type like `Comparable a, Comparable b => ...`.

**Comment by jeremy-w** [comment]
It looks like type variables are introduced in [Model the Problem: Recursive Data Structures](http://elm-lang.org/guide/model-the-problem#recursive-data-structures):

> List also takes a type as an argument, so we can create (List Int) or (List String) or whatever.

So some place after introducing type variables, I would suggest discussing **"restricted type variables",** with verbiage like:

> `List a` has a type variable `a`. Some type variables in Elm are special: Unlike normal type variables such as `a` in `List a`, they can only take on certain types as values. These types have a property that interacts with Elm's operators to ensure an operator like `<` always does what you'd expect. The restricted type variables as of Elm vX.Y, and the types allowed to substitute for them, are:
>
> - comparable: Comparable types are Int, Float, Char, String (also lists or tuples of these types). These types can be used with the comparison operators `(<)`, `(>)` among [others](package.elm-lang.org/packages/elm-lang/core/latest/Basics#comparison).
> - …
>
> Whenever you see two occurrences of `comparable` in a type annotation, both must have the same type substituted. If you wanted to require two, possibly different, `comparable` types be provided to a function, you would append a tickmark/prime (`'`) to the second type, like `f : comparable -> comparable' -> Bool`.

**Comment by evancz** [comment]
Will add explanations of this in http://guide.elm-lang.org/ as I make progress on the content.

**Comment by Wexcode** [comment]
An explanation was added here: https://guide.elm-lang.org/types/reading_types.html
