### ISSUE TITLE
Line number off-by-one in web editor

### ISSUE THREAD

**Issue by jameshfisher** [elm-lang/elm-lang.org#200]
## Steps to reproduce

1. Go to http://elm-lang.org/try
2. Enter the text:

   ```
   x = 3 + "foo"
   ```

3. Click "Compile" button

## Expected behavior

Same as using `elm-make`, as in:

```
> elm-make test.elm

Error in test.elm:

Type mismatch between the following types on line 1, column 5 to 14:
[...]
```

## Actual behavior

Line number in error is off-by-one:

```
Type mismatch between the following types on line 2, column 5 to 14:
[...]
```

**Comment by evancz** [comment]
As part of some work on the compiler, we can give errors as JSON now, so we adjust the region to be correct now. Thanks for reporting this!
