### ISSUE TITLE
Web editor handles Unicode programs incorrectly

### ISSUE THREAD

**Issue by jameshfisher** [elm-lang/elm-lang.org#202]
### Steps to reproduce

Copy this program into [the web editor](http://elm-lang.org/try) and compile:

```
import Text
import String
main = Text.plainText (String.fromChar '░')
```

### Expected behavior

The same as this program:

```
import Text
main = Text.plainText "░"
```

or this program:

```
import Text
import String
main = Text.plainText (String.fromChar '\x2591')
```

### Actual behavior

This parse error:

```
Parse error at (line 4, column 40):
unexpected "'"
expecting whitespace, a newline or closing paren ')'
```

See https://github.com/elm-lang/elm-compiler/issues/858 for some discussion.

**Comment by evancz** [comment]
Thank you for the report! It should be resolved now. Here's an updated example that now works:

```elm
import Graphics.Element exposing (..)
import Text
import String

main = leftAligned (Text.fromString (String.fromChar '░'))
```
