### ISSUE TITLE
Undocumented tokens throws javascript exception in live editor

### ISSUE THREAD

**Issue by lepinay** [elm-lang/elm-lang.org#225]
You get theses if you click on a token in the editor which doesn't have any documentation associated with:
Uncaught TypeError: Cannot read property 'values' of null editor.js?0.11:221
2Uncaught TypeError: Cannot read property 'values' of null editor.js?0.11:221

**Comment by evancz** [comment]
This should be resolved in [the rewrite of the site](http://elm-lang.org/try)!
