### ISSUE TITLE
Loading http://elm-lang.org/learn/Interactive-UI-Elements.elm yields a '404' Page Not Found error.

### ISSUE THREAD

**Issue by teehemkay** [elm-lang/elm-lang.org#230]
I think the problem is that frontend/public/learn/Interactive-UI-Elements.elm has not yet been upgraded to Elm 0.14

**Comment by doppioslash** [comment]
Yes, that's the problem.
Someone has made a PR for that, #227

**Comment by teehemkay** [comment]
Cool, thanks.

**Comment by sroccaserra** [comment]
Hi, this is a duplicate for issue #201.

Cheers!

**Comment by sdegutis** [comment]
Right, this is more due to #227 than #201.

**Comment by evancz** [comment]
Removed the link entirely in favor of https://github.com/evancz/elm-architecture-tutorial, check it out! It's better!
