### ISSUE TITLE
Ports documentation could be clearer about initialization

### ISSUE THREAD

**Issue by kasbah** [elm-lang/elm-lang.org#232]
Just thought I would mention this because it confused me for quite a bit. I didn't notice that in the examples the worker/embed/fullscreen function is called with an initialisation object. I think it would be good to mention that in `Ports.elm`. If you don't do it you get the js error 

```
Uncaught Error: Initialization Error: port 'addUser' was not given an input!
``` 

which does make sense in retrospect but just made me ask "what do you mean an input?" at the time.

**Comment by gsingh93** [comment]
I had the same issue and was confused by the error message.

**Comment by fobos** [comment]
The same for me. Only by investigating compiled sources in `elm.js` file I understand how to init ports.

**Comment by danyx23** [comment]
I was also stumped by this. There is now a PR open to document this better: #476

**Comment by evancz** [comment]
This is not a thing anymore. There is not initialization of ports.
