### ISSUE TITLE
Library Design Principles is not found

### ISSUE THREAD

**Issue by eksperimental** [elm-lang/elm-lang.org#234]
this one arose from a conversation in https://github.com/elixir-lang/elixir-lang.github.com/issues/310

https://github.com/elm-lang/elm-lang.org/blob/master/frontend/public/Learn.elm

````
[Library Design Guidelines](http://library.elm-lang.org/DesignGuidelines.html) &mdash; creating pleasant and consistent libraries in Elm
````
that link is dead.

**Comment by eksperimental** [comment]
same with http://library.elm-lang.org/Documentation.html

**Comment by evancz** [comment]
They have been moved to the following locations:

http://package.elm-lang.org/help/design-guidelines
http://package.elm-lang.org/help/documentation-format

I am not able to do a redirect unfortunately. Is that enough information to resolve this issue?

**Comment by eksperimental** [comment]
yes, i see they have been fixed now. thank you!
