### ISSUE TITLE
Signal -> Input link 404s

### ISSUE THREAD

**Issue by tomjaguarpaw** [elm-lang/elm-lang.org#237]
This page

http://elm-lang.org/learn/Interactive-UI-Elements.elm

linked from here

http://elm-lang.org/Learn.elm

gives me a 404.

**Comment by sebastiant** [comment]
Duplicate of #230

**Comment by evancz** [comment]
That link has been removed in favor of https://github.com/evancz/elm-architecture-tutorial, check that out instead!
