### ISSUE TITLE
Dependency (Text module specifically) not included in generated Javascript

### ISSUE THREAD

**Issue by imeckler** [elm-lang/elm-lang.org#247]
I've written a program [here](https://github.com/imeckler/turing-elm/tree/9fafd610871d0635c6f4c71cfffa65848c8ef873).

When compiled using `elm-make Main.elm --output main.html`, the generated Javascript does not include the Text module, which is apparently a dependency of Main. As a result, there is the error
```
Elm.Native.Text is undefined
```

If I add the import `import Text` to Main, everything works fine.

**Comment by evancz** [comment]
I think this was fixed by @mgold. Is that correct? If so, it'll be out in the next release.

**Comment by mgold** [comment]
Yes, and you've already discovered the workaround. Thanks for reporting!
