### ISSUE TITLE
How about losing 'alias' keyword?

### ISSUE THREAD

**Issue by theburningmonk** [elm-lang/elm-lang.org#249]
In the example

`type alias Point = { x : Float, y : Float }`

why does it matter to me that Point is an alias or not? It gives me a type that I can reference later on, and that's what's important here, the fact that it's an alias is an implementation detail that I shouldn't have to be aware of.

Also, without understanding that Records doesn't need to be defined ahead of time (which is different to other languages such as Erlang and F#) might cause confusion, "what is Point an alias of? I haven't defined a type that has X and Y yet".

Lastly, and it might just be me, when I define a number of types in quick succession (some union and some record) I often forget the alias keyword as I need to do a mental switch/check every time and that feels like unnecessary cognitive burden (one that gets picked up by the compiler quickly enough and easy to rectify but probably shouldn't be there in the first place).

Thoughts?

**Comment by evancz** [comment]
I think this is best asked on the mailing list where a bunch of people can give an answer, so I'm going to close it here.

The short version is that `type` creates a new type, whereas `type alias` is just an alias and no new types are created. Folks on the list can say more.

**Comment by johnpmayer** [comment]
Note that alias is pretty important. Consider the following in a world
where alias does not exist:

type Baz = BazC
type Bar a = BarC a
type Foo = Bar Baz

Is Foo a new type with a data constructor Bar which takes a Baz, or is Foo
a type alias for the type constructor Bar applied to the type Baz?
