### ISSUE TITLE
It's not clear if Elm's GUI is being deprecated.

### ISSUE THREAD

**Issue by sdegutis** [elm-lang/elm-lang.org#251]
All the talk and hype about [elm-html](https://github.com/evancz/elm-html) makes it look like elm-html is the future of using Elm, and its canvas-based custom UI is a second-class citizen, or at least will be very soon. Can you clarify this situation, maybe with a FAQ?

**Comment by evancz** [comment]
Discussed here: https://groups.google.com/forum/#!searchin/elm-discuss/elm-html$20elements/elm-discuss/zj4-4b0j8_I/TrCl0qaDnswJ

Maybe do a PR about the FAQ if you know how it should fit in?
