### ISSUE TITLE
FAQ should be split into two new pages

### ISSUE THREAD

**Issue by sdegutis** [elm-lang/elm-lang.org#252]
I was looking for differences between Elm vs. JavaScript, and and Elm vs. Haskell, but couldn't find them on [the Learn page](http://elm-lang.org/Learn.elm). I eventually found them in [this FAQ](http://elm-lang.org/learn/FAQ.elm). I think it should be split into two separate pages, "Differences from Haskell" and "Differences from JavaScript", so that it's easier for people to find. I can do this and submit a PR if need-be.

**Comment by evancz** [comment]
[The new docs page](http://elm-lang.org/docs) links to [a document](http://elm-lang.org/docs/from-javascript) specifically for JS users. So that old split FAQ no longer exists.
