### ISSUE TITLE
links to blog posts on testblogpleaseignore.com are down

### ISSUE THREAD

**Issue by Dobiasd** [elm-lang/elm-lang.org#256]
The following five links are affected:

https://github.com/elm-lang/elm-lang.org/blob/df01a1e56c3ac4528cf3a0ecc8d542f4e0aa9cbf/frontend/public/learn/Escape-from-Callback-Hell.elm#L492

https://github.com/elm-lang/elm-lang.org/blob/df01a1e56c3ac4528cf3a0ecc8d542f4e0aa9cbf/frontend/public/learn/FAQ.elm#L50

https://github.com/elm-lang/elm-lang.org/blob/df01a1e56c3ac4528cf3a0ecc8d542f4e0aa9cbf/frontend/public/Blog.elm#L65

https://github.com/elm-lang/elm-lang.org/blob/df01a1e56c3ac4528cf3a0ecc8d542f4e0aa9cbf/frontend/public/Blog.elm#L66

https://github.com/elm-lang/elm-lang.org/blob/df01a1e56c3ac4528cf3a0ecc8d542f4e0aa9cbf/frontend/public/Blog.elm#L67

Are these articles still online somewhere else?

**Comment by evancz** [comment]
I lost access to the server behind testblogpleaseignore, and it seems that it had a restrictive robots.txt so they did not get saved by the wayback machine. So it seems they are lost :(
