### ISSUE TITLE
`<<` operator isn't documented in syntax reference

### ISSUE THREAD

**Issue by jafrog** [elm-lang/elm-lang.org#257]
There's no mention of the `<<` operator on the syntax reference page.

**Comment by stefanodacchille** [comment]
Have you already seen [this page](http://package.elm-lang.org/packages/elm-lang/core/1.1.1/Basics#<<) ?

**Comment by evancz** [comment]
I don't really want to emphasize the function composition operators too much, I think `(<|)` and `(|>)` are better in general.
