### ISSUE TITLE
List of buggy or broken examples

### ISSUE THREAD

**Issue by TheSeamau5** [elm-lang/elm-lang.org#263]
- [x] http://elm-lang.org:1234/edit/examples/Reactive/Touches.elm 
- [x] http://elm-lang.org:1234/edit/examples/Reactive/CharPressed.elm
- [x] http://elm-lang.org:1234/edit/examples/Reactive/Taps.elm 
- [x] http://elm-lang.org:1234/edit/examples/Reactive/Draw.elm
- [x] http://elm-lang.org:1234/edit/examples/Reactive/KeepIf.elm
- [x] http://elm-lang.org:1234/edit/examples/Reactive/Log.elm (open the console to see that it's broken)
- [x] http://elm-lang.org:1234/edit/examples/Reactive/Title.elm (same here)
- [x] http://elm-lang.org:1234/edit/examples/Reactive/Redirect.elm (same here)
- [x] http://elm-lang.org:1234/edit/examples/Intermediate/Plot.elm
- [x] http://elm-lang.org:1234/edit/examples/Intermediate/SlideShow.elm
- [x] http://elm-lang.org:1234/edit/examples/WebGL/Triangle.elm
- [x] http://elm-lang.org:1234/edit/examples/WebGL/Cube.elm
- [x] http://elm-lang.org:1234/edit/examples/WebGL/Thwomp.elm
- [x] http://elm-lang.org:1234/edit/examples/WebGL/FirstPerson.elm

**Comment by mgold** [comment]
:clap:

**Comment by evancz** [comment]
Great, thank you @TheSeamau5! All of them should be fixed *or* they should be inaccessible.
