### ISSUE TITLE
Attempting to run run-elm-website for the first time fails.

### ISSUE THREAD

**Issue by bstro** [elm-lang/elm-lang.org#269]
I just went through the setup instructions for installing and running the elm-lang.org repo locally. Everything went fine until the last step. Upon running `./dist/build/run-elm-website/run-elm-website`, I receive the following:

```
Initializing Server
............................................................................................................................................................
run-elm-website: build: getDirectoryContents: does not exist (No such file or directory)
```

**Comment by evancz** [comment]
Sorry for the trouble on this :/

I don't know how to reproduce this, and the website has been updated significantly today, so the same error should not be happening with the new stuff.

If you run into trouble again, please report it and let us know: what OS you are using, what version of ghc and cabal you have, the particular commands you ran to get to this point. Lots of weird things can go wrong in the build process unfortunately :/
