### ISSUE TITLE
Hysterisis in rendering due to horizontal scroll bar

### ISSUE THREAD

**Issue by kaaloo** [elm-lang/elm-lang.org#273]
I would like to report an issue that I see fairly frequently.  Sometimes when an elm application is displayed at certain window dimensions it will go in an infinite loop where in one page refresh a horizontal scroll bar is displayed and in the next one it is not and so on.  The loop is caused by the setTimeout call in the resizeIfNeeded function.

So for instance here we have some elm package documentation displayed at a window size of 1765 x 1182 pixels.  The Elm window dimensions are 1167 x 711 as seen in chrome dev tools.

![elm package documentation - google chrome_044](https://cloud.githubusercontent.com/assets/67010/7593157/43697256-f8d8-11e4-8cb3-65c1c70b0592.jpg)

The next time around it displays with a horizontal scroll bar as below and the Elm window dimensions are 1177 x 711.

![elm package documentation - google chrome_045](https://cloud.githubusercontent.com/assets/67010/7593181/7b6ffecc-f8d8-11e4-8381-92d96f9ec1a0.jpg)

Resizing the browser window leads until the loop exits gets you to a stable display but it is a nuisance.

Luis

**Comment by evancz** [comment]
Should not happen on any Elm sites anymore.
