### ISSUE TITLE
Under which GHC version / libraries is the 0.15 branch compilable?

### ISSUE THREAD

**Issue by Apanatshka** [elm-lang/elm-lang.org#277]
I've tried my arch-based install, using ghc 7.10, and my older Windows install which has Haskell Platform 2013.2.0.0 (ghc 7.6.3) but the dependencies can't be resolved. I'm using sandboxes and I nuked my locally installed packages, so I'm out of ideas :expressionless: 
Here's what I get on Windows:
```
Resolving dependencies...
cabal.exe: Could not resolve dependencies:
trying: elm-website-0.1.0.2 (user goal)
trying: snap-server-0.9.5.1 (dependency of elm-website-0.1.0.2)
trying: MonadCatchIO-transformers-0.3.1.3 (dependency of snap-server-0.9.5.1)
trying: transformers-0.4.3.0/installed-f99... (dependency of
MonadCatchIO-transformers-0.3.1.3)
trying: snap-core-0.9.7.0 (dependency of elm-website-0.1.0.2)
trying: regex-posix-0.95.2/installed-a7b... (dependency of snap-core-0.9.7.0)
trying: regex-base-0.93.2/installed-6a5... (dependency of
regex-posix-0.95.2/installed-a7b...)
next goal: mtl (dependency of elm-website-0.1.0.2)
rejecting: mtl-2.2.1/installed-8f1... (conflict: regex-base =>
mtl==2.1.2/installed-678...)
rejecting: mtl-2.1.2/installed-678... (conflict:
transformers==0.4.3.0/installed-f99..., mtl =>
transformers==0.3.0.0/installed-df1...)
rejecting: mtl-2.2.1, 2.2.0.1, 2.2, 2.1.3.1, 2.1.2, 2.1.1, 2.1, 2.0.1.1,
2.0.1.0, 2.0.0.0, 1.1.1.1, 1.1.1.0, 1.1.0.2, 1.1.0.1, 1.1.0.0, 1.0 (conflict:
regex-base => mtl==2.1.2/installed-678...)
Backjump limit reached (change with --max-backjumps).
```

**Comment by evancz** [comment]
I'm using 7.8.3 and I haven't tried out 7.10 yet. I'll see if the mtl dependency can go higher?

**Comment by Apanatshka** [comment]
That would be great. In the mean time I'm going to see if I can download a Haskell Platform for Windows with ghc 7.8.3.

**Comment by evancz** [comment]
Also, did you try this advice `Backjump limit reached (change with --max-backjumps)`?

I know there's a solution because it works for me. You can also try adding constraints to the .cabal file to help guide things

**Comment by Apanatshka** [comment]
The standard backjump value is 200. I tried it with 2000 but it didn't
yelp. I don't have experience with adding constraints to the cabal file.
But updating my Haskell installation is a good idea anyway.

**Comment by BethAr** [comment]
@Apanatshka, I've found that I often have conflicts when using the Haskell Platform, because of the bundled libraries. I don't know how this applies to Elm, but you could try [MinGHC](https://github.com/fpco/minghc), which packs only the internal GHC libraries. Most importantly, MinGHC is capable of compiling Network, which is a nightmare for Windows users.

**Comment by Apanatshka** [comment]
Thanks for the tip @BethAr. I installed Haskell Platform 2014.2.0.0 to see if it would work. Elm-Platform master installed without a hitch, then I had to --force-reinstalls this repo while building it in the same sandbox. But whatever, they're all built, and I'm running the 0.15 branch of elm-lang.org locally now :)
