### ISSUE TITLE
site is blank via Opera Mini Android

### ISSUE THREAD

**Issue by raould** [elm-lang/elm-lang.org#280]
At least the old version. 7.6.40234, on my Android 4.1 device. The pages are mostly blank; occasionally some title text gets through. Just downloaded and tried the new Opera Mini and it also failed the same way. 8.0.1807.91281.

**Comment by evancz** [comment]
Are you able to pin it down to anything more specific than that? Is it possible to check out the console and see if some errors are being thrown? I could imagine some browser API is not supported or something?

**Comment by evancz** [comment]
Is this true with the new site?

**Comment by raould** [comment]
Looks a lot better, seems like most everything is there! Thank you.

**Comment by evancz** [comment]
Cool, thanks for the report!
