### ISSUE TITLE
WIP: website revamp

### ISSUE THREAD

**Issue by evancz** [elm-lang/elm-lang.org#283]
I have slowly been moving things over to the 0.15 branch which has a simpler style and hopefully a bit easier to navigate. Things left are:

  * [x] Migrate examples over
  * [x] Migrate learn pages over
  * [ ] Do responsive CSS stuff to make it all look nice on small screens
  * [x] Update examples to cover some more modern cases
  * [x] Adapt learn pages to fit in a more book-like format

The larger goal is to make the learning resources better overall. This means making the documentation for types and tasks and ports and such fit together better. It also means refreshing all the examples. That may mean getting rid of some and creating new ones. It also means figuring out a way to make the path through examples clearer.

**Comment by Apanatshka** [comment]
So I want to help migrate examples. Is the old subdirectory structure of the examples going to be kept? 
I see two examples directly in `src/examples` on the 0.15 branch. But when I run the website, I can't find a URL that accessed those files as an editor. I quickly looked at the backend code but I don't know Snap.. What URL should I use to actually access an example in the split view with editor?

**Comment by evancz** [comment]
I've actually been curating as I move them over, and now that I'm in the swing of it, I think the process works well. It takes time, but I'm really happy with the results.

I think if you can figure out how to make things responsive (CSS that handles different sizes) that'd be the biggest help. I know that's not your specialty, but I think it's important and totally not blocked by me.

**Comment by TheSeamau5** [comment]
I've noticed that on mobile everything looks tiny. I don't know about how the Haskell framework works, but it could be valuable to add this meta tag in the head: 

```html
<meta name="viewport" content="width=device-width, initial-scale=1">
```

Hopefully it could help make things more responsive.


Resources about meta viewport: 
https://developer.mozilla.org/en/docs/Mozilla/Mobile/Viewport_meta_tag
https://css-tricks.com/snippets/html/responsive-meta-tag/

**Comment by evancz** [comment]
I'd like to add that, but not all pages will play nice. Many need 600px and cannot go lower as is. I think we can make some changes in how [this](https://github.com/elm-lang/elm-lang.org/blob/0.15/src/shared/Center.elm) works and then it'd be fine.

From there, we can add in that meta tag [here](https://github.com/elm-lang/elm-lang.org/blob/0.15/src/backend/Generate.hs#L81) (or around there...)

**Comment by evancz** [comment]
Okay, I'm gonna open an issue specifically about making things nicer on small devices.
