### ISSUE TITLE
Extensible Records: last sentence.

### ISSUE THREAD

**Issue by BethAr** [elm-lang/elm-lang.org#284]
At the [Extensible Records](http://elm-lang.org/learn/Records.elm) docs, the last sentence (or line) is clipped in Chrome and Firefox.

**Comment by thSoft** [comment]
Duplicate of https://github.com/elm-lang/elm-lang.org/issues/198.

**Comment by BethAr** [comment]
It seems a new version of the website is being built, so this is inconsequential.

**Comment by evancz** [comment]
Yeah, one of the goals with the redo was to get rid of this issue, which showed up on a couple pages for reasons that are not entirely clear to me. Thanks for reporting this!
