### ISSUE TITLE
Submit the CodeMirror mode to the main CodeMirror distribution?

### ISSUE THREAD

**Issue by marijnh** [elm-lang/elm-lang.org#292]
Elm is great, and popular enough to have its mode distributed with CodeMirror. If you just tell me that it's okay to move resources/codemirror-3.x/mode/elm/elm.js under [CodeMirror's license](http://codemirror.net/LICENSE) (MIT), I'll take care of the rest.

**Comment by evancz** [comment]
Yeah, it is okay to move it over there under the MIT license!

**Comment by marijnh** [comment]
Wonderful. See https://github.com/codemirror/CodeMirror/commit/90bc10bf216d82f08438f60cf315ce83f9b73c5f

**Comment by evancz** [comment]
Awesome, thank you! :D
