### ISSUE TITLE
Add Linux install instructions via npm?

### ISSUE THREAD

**Issue by jvoigtlaender** [elm-lang/elm-lang.org#294]
The [Install page](http://elm-lang.org/Install.elm) currently says that on other platforms than Windows and Mac, one needs to build from source. However, actually one can use the npm installer on Linux. This has low discoverability at the moment, so for example [surprised](https://github.com/elm-lang/elm-platform/issues/48#issuecomment-106575861) @Fresheyeball.

Possible instructions could be that with npm installed, one can do `sudo npm install --global elm` and set the  `ELM_HOME` environment variable to `/usr/local/lib/node_modules/elm/share`. That's it.

**Comment by evancz** [comment]
Thanks for doing this, I think it'll save people a lot of time and trouble!
