### ISSUE TITLE
People installing from source should be told about ELM_HOME

### ISSUE THREAD

**Issue by jvoigtlaender** [elm-lang/elm-lang.org#297]
Neither the [section about bulding from source on the install page](http://elm-lang.org/Install.elm#build-from-source) nor the [script linked to from there](https://github.com/elm-lang/elm-platform/blob/master/installers/BuildFromSource.hs#L1-L31) tell the user anything about `ELM_HOME`. But without setting that environment variable appropriately, they will not be able to use the debug mode of `elm-reactor`.

**Comment by jvoigtlaender** [comment]
The [README of https://github.com/elm-lang/elm-platform](https://github.com/elm-lang/elm-platform/blob/master/README.md) doesn't either.

**Comment by evancz** [comment]
If you install with cabal, it should not need ELM_HOME. Are you observing that things actually break when using those instructions?

**Comment by jvoigtlaender** [comment]
Oh, sorry for the noise, then. I was just making this suggestion based on systematics (other install instructions need this), ignorant of the fact that it may not be needed for cabal installs. (I did my early Elm installs with cabal, but don't remember what I did or did not have to do about paths.)

So, my "should" in the issue title was clearly too strongly worded, given my lack of recent first hand experience. :-) Anyway, closing this.

**Comment by jvoigtlaender** [comment]
Actually, back in December, @pseudonom had exactly this problem: building from source, then running into an error complaining about  `ELM_HOME` not being set. That issue (https://github.com/elm-lang/elm-platform/issues/27) is still open, so maybe this one here is not really obsolete either. Re-opening.

**Comment by evancz** [comment]
The build from source instructions are going to live at elm-platform, so we should talk about this there. I'll add a note about ELM_HOME, but as I describe in more depth [here](https://github.com/elm-lang/elm-platform/issues/27#issuecomment-111352127) it should not come up when building through cabal.
