### ISSUE TITLE
improvement for Package docs breadcrumbs information architecture / human urls

### ISSUE THREAD

**Issue by raould** [elm-lang/elm-lang.org#299]
1) go to http://package.elm-lang.org/packages/elm-lang/core/2.0.1/Array
2) see "elm-lang / core / Array" at the top of the page
3) wonder why the "elm-lang" part is not a link, only the "core" is
4) look at the url and think "well, a human url layout of the site would mean http://package.elm-lang.org/packages/elm-lang would be a real, reasonable, page, maybe a table of contents or something.
4) go to http://package.elm-lang.org/packages/elm-lang and get a 404
5) be a little sad

**Comment by evancz** [comment]
I'd like to show all the versions about the library on that page and some stats about the package over time. Like "how many people use each version of the library?" or "what's the difference between version A and version B?"

**Comment by evancz** [comment]
Okay, moved this issue over to the appropriate repo, thanks for the report!
