### ISSUE TITLE
"Using Signals" refers to `keepWhen`, which has been removed.

### ISSUE THREAD

**Issue by dbeecham** [elm-lang/elm-lang.org#301]
> Sometimes it is useful to filter certain updates, though it does not come up super frequently. For example, lets say I want to have a signal that represents dragging the mouse. I could use keepWhen for this:

`keepWhen` was removed in 2.0.0.

How do you do 'keepWhen' these days?

**Comment by robwhitaker** [comment]
I've been missing that `keepWhen` functionality. Though, you could probably implement your own doing something like.

```
keepWhen : Signal Bool -> a -> Signal a -> Signal a
keepWhen pred default sig = Signal.map2 (\p s -> if p then s else default) pred sig
```

Then again, I don't know what the thinking was behind removing it, so perhaps this is not recommended.

**Comment by evancz** [comment]
It exists in @Apanatshka's signal-extra library [here](http://package.elm-lang.org/packages/Apanatshka/elm-signal-extra/5.1.0/Signal-Extra#keepWhen).

I'm working on a new version of the website, and the "Using Signals" content has been updated to not use that example anymore.

Thanks for the report!
