### ISSUE TITLE
Run elm-lang.org locally

### ISSUE THREAD

**Issue by law-liet** [elm-lang/elm-lang.org#302]
I followed all the steps in README, but I got this error at the last step: run-elm-website: build: getDirectoryContents: does not exist (No such file or directory).  
I got into the run-elm-website directory and run the script again. Then I got this error: run-elm-website: resources/elm-runtime.js: openFile: does not exist (No such file or directory).
But I checked that elm-runtime.js is fine inside resources/.

**Comment by evancz** [comment]
I'm not sure how to debug based on this description. I just did a new release of the website and updated the build instructions.

If you run into trouble again, please show exactly the commands you ran and your OS. I think that'll make it easier to help.

Also, sorry for the slow response!
