### ISSUE TITLE
request: a place for Elm community apps

### ISSUE THREAD

**Issue by robwhitaker** [elm-lang/elm-lang.org#303]
A section should be added to the site (whether on the examples page or elsewhere) for Elm applications submitted by the community. This would be a great resource for developers as well as a solid showcase of all the cool stuff that Elm can do.

Potential apps to add include:

  - https://github.com/Dobiasd/EditGym
  - https://github.com/robwhitaker/Elm-Planner
  - https://github.com/elm-lang/elm-lang.org
  - https://github.com/elm-lang/package.elm-lang.org
  - https://github.com/Dobiasd/RedditTimeMachine
  - https://github.com/Dobiasd/Barcode-Generator

Please add a comment in this issue if you think others should be on this list!

**Comment by thSoft** [comment]
builtwithelm.co is already linked on the homepage, which serves this purpose.

**Comment by jvoigtlaender** [comment]
@robwhitaker, does builtwithelm.co address your request? Can you close the issue now?
