### ISSUE TITLE
Syntax coloring would be great

### ISSUE THREAD

**Issue by raould** [elm-lang/elm-lang.org#306]
colored syntax helps a lot, this:
https://github.com/TheSeamau5/elm-check

reads a lot better to me than this:
http://package.elm-lang.org/packages/TheSeamau5/elm-check/3.0.1

**Comment by evancz** [comment]
Can you retarget this to [the package repo](https://github.com/elm-lang/package.elm-lang.org/)? We run different servers, which is why elm-lang.org was down but package.elm-lang.org was not.
