### ISSUE TITLE
WIP: responsive design for small screens

### ISSUE THREAD

**Issue by evancz** [elm-lang/elm-lang.org#307]
There are a few things we need to do before turning this on:

  - [ ] make sure [the top bar](https://github.com/elm-lang/elm-lang.org/blob/master/src/shared/TopBar.elm) can resize in a pleasant way
  - [ ] make [the centering library](https://github.com/elm-lang/elm-lang.org/blob/master/src/shared/Center.elm) able to handle widths under 600px

Not sure if there are more!

**Comment by wetmore** [comment]
Besides the top bar, are you happy with how the homepage looks? It benefits IMO by throwing

`<meta name="viewport" content="width=device-width, initial-scale=1,user-scalable=no">`

into the head tag, but this doesn't fall under any of the current tasks. You can see what I mean by opening the Chrome devtools, right-clicking the head tag, selecting "edit as HTML" and pasting that in after the opening head tag.

I know one would do this differently in Elm but this is a quick way to see the effect.

**Comment by evancz** [comment]
Yeah, that's what we'll do once all the bullets are checked! I just want to track blockers in this issue.

**Comment by gamecubate** [comment]
bump on this. The current documentation has quite small a font size on mobile, making it a bit difficult to read. Adding "<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />" would solve this.

**Comment by evancz** [comment]
This checklist is clearly not helping get things done. Should add this to https://github.com/elm-lang/projects instead.
