### ISSUE TITLE
Sprite images in mario and adventure examples are not changing

### ISSUE THREAD

**Issue by alexiamcdonald** [elm-lang/elm-lang.org#313]
It appears that the sprite image for walking, running and moving in different directions are not updating in the examples (walk, jump, and run around):

- http://elm-lang.org/examples/adventure
- http://elm-lang.org/examples/short-mario

Maybe the wrong files were uploaded? We looked in the repository and the images seem to be correct however.

**Comment by BethAr** [comment]
I can't reproduce this. The sprites change correctly for me. (Chrome on Windows 7)

**Comment by bjz** [comment]
Breaks for me on Firefox 40.0a2 (2015-06-15) on OS X

**Comment by alexiamcdonald** [comment]
I've checked on Windows 8.1 Chrome works but it breaks on Firefox.

**Comment by BethAr** [comment]
I confirm it breaks on Firefox on Windows 7 as well.

**Comment by tractorjack** [comment]
I confirm it breaks on Firefox 40.0.3 on Windows 7

**Comment by hayohayo** [comment]
The same here on Firefox 42.0 on Mac. Works fine in Chrome though. My observation is - Chrome seems to be properly caching all gifs, while Firefox spams requests (not always though).

**Comment by evancz** [comment]
Not a problem at the moment. Will see when that example is revived.
