### ISSUE TITLE
Redirect error in http://elm-lang.org/docs/syntax

### ISSUE THREAD

**Issue by i-e-b** [elm-lang/elm-lang.org#316]
In http://elm-lang.org/docs/syntax there is a link in the “Mapping” section to http://elm-lang.org/blog/announce/0.7.elm#do-you-even-lift Following this link in Chrome results in a *Too Many Redirects* error screen.

Doing a raw `GET /blog/announce/0.7.elm#do-you-even-lift HTTP/1.1`  results in a 200 and a reasonable looking HTML document,
but `GET /blog/announce/0.7.elm HTTP/1.1` results in :

```
HTTP/1.1 301 Moved Permanently
Content-Length: 0
Server: Snap/0.9.5.1
Date: Thu, 18 Jun 2015 14:13:08 GMT
Location: /blog/announce/0.7.elm
```

**Comment by BethAr** [comment]
Confirmed in Chrome, Windows 7.

**Comment by jvoigtlaender** [comment]
This has been fixed by [this commit](https://github.com/elm-lang/elm-lang.org/commit/a14f93fae08e4b3973d77de6fb5f2252c9c3f065), so the issue can be closed.
