### ISSUE TITLE
Element in Pong and Adventure shaking in IE

### ISSUE THREAD

**Issue by alexiamcdonald** [elm-lang/elm-lang.org#320]
The entire element appears to shake in Internet Explorer (Windows 8) when pressing the keyboard to move the player in the examples:

- http://elm-lang.org/examples/pong
- http://elm-lang.org/examples/adventure

I think it only happens to examples where the element `container` is set as `middle` from what I've seen so far

I recorded an example of what I encounter in Adventure:
![middleerror](https://cloud.githubusercontent.com/assets/8427242/8270153/d3041a06-1813-11e5-9ad0-64da61033013.gif)

**Comment by alexiamcdonald** [comment]
I have reduced it down to this bouncing A. Pressing the keyboard arrows randomly bounces the element in IE.

```elm
import Graphics.Element exposing (Element, container, middle)
import Keyboard
import Markdown
import Window

view : (Int,Int) -> { x : Int, y : Int } -> Element
view (w,h) _ =
    container w h middle <| Markdown.toElement "A"
      
main : Signal Element
main =
  Signal.map2 view Window.dimensions Keyboard.arrows
```

**Comment by evancz** [comment]
What version of IE is this exactly?

**Comment by alexiamcdonald** [comment]
Internet Explorer 11

**Comment by evancz** [comment]
Okay, the shaking thing is "resolved" in the sense that window just works totally different now. Thanks for hunting this down and making a really small example though!
