### ISSUE TITLE
Hot Swap throws an error

### ISSUE THREAD

**Issue by maxhoffmann** [elm-lang/elm-lang.org#321]
On http://elm-lang.org/examples/hello-html clicking the `Hot Swap` button throws this error:

`Uncaught TypeError: Cannot read property 'swap' of undefined`

For a good first time impression I’d recommend removing the button or fixing it. :)

**Comment by jorinvo** [comment]
This seems to be a general problem and related to #176.

**Comment by evancz** [comment]
Not in the editor anymore.
