### ISSUE TITLE
Add proper get-started-page (again?)

### ISSUE THREAD

**Issue by jvoigtlaender** [elm-lang/elm-lang.org#327]
The installers provide the link http://elm-lang.org/Get-Started.elm. Currently it redirects to http://elm-lang.org/docs, but that page does not really tell the user how to get started with Elm in terms of how to build/run a program. 

How do I compile a program? What is elm-reactor, what are the roles of the other executables installed, etc.? These questions are not answered there, and as [evidenced in this thread](https://groups.google.com/d/msg/elm-discuss/-JqrhSDZyn4/fTge-omsOtUJ), this can be an impediment for people starting out.

I vaguely remember that there previously was a get-started-page that provided such info. Or maybe that was instead some README of one of the various repos? In any case, it seems worthwhile to have http://elm-lang.org/Get-Started.elm not be a redirect to http://elm-lang.org/docs, but instead a page with info about what got just installed (and then possibly a link from that page to http://elm-lang.org/docs). Incidentally, Gil Mizrahi's [blog post](http://www.gilmi.xyz/post/2015/07/04/starting-elm) pointed to in [this thread](https://groups.google.com/d/msg/elm-discuss/GgUFRRfAbgU/W0U_1QBO3xcJ) fits the bill quite well. Maybe it's even possible to turn that post into something for http://elm-lang.org/Get-Started.elm?

**Comment by chasm** [comment]
The Reactivity tutorial provides lots of code. No idea where to put it. No idea how to start the app. No idea how to compile it.

No problem! I'll just use the handy contact form to . . . uh, oh. No contact form. No contact info. No link to GitHub. No nothing. Not even comments on the blog pages. The site exists in its own world, completely disconnected from the users.

I guess the Elm folks really want to keep the newbies out.

Epic fail. Absolutely epic.

**Comment by soupi** [comment]
@chasm though you do have a community tab with links to the mailing list, subreddit, IRC and twitter.

**Comment by chasm** [comment]
None of which are appropriate for a bug report.

Fail is fail. Best response is a mea culpa and a quick fix.

**Comment by jvoigtlaender** [comment]
[Further evidence that adding something along the lines in my comment above may be a good idea.](https://groups.google.com/d/msg/elm-discuss/tIuL4aMgJUM/uVcm3lfUBQAJ)

**Comment by jvoigtlaender** [comment]
Another related [post on the mailing list](https://groups.google.com/forum/#!topic/elm-discuss/Y7n8TA7ZlHw).

**Comment by evancz** [comment]
I wrote [this](https://gist.github.com/evancz/318b5f978d25e90916cf) at some point. It kind of covers things. The new elm-architecture-tutorial also does a better job.

Can you do a PR? I don't know the right thing, I guess something bad happened in Hackage recently so I am trying to deal with that right now. Maybe go through the repo history and revive the old page? Just do a PR and we can work from there.

**Comment by jvoigtlaender** [comment]
Is GitHub dropping comments? I had written one here saying that I still think that [Gil Mizrahi's blog post](http://www.gilmi.xyz/post/2015/07/04/starting-elm) would be the best start here, and that I would ask Gil whether the willingness to make a PR from it is still there. (Which I have now done.)

**Comment by jvoigtlaender** [comment]
For the record: I don't know exactly what was on the original Get-Started page, and couldn't immediately locate it in the repo. But from the mailing list threads above it seems clear to me that something that should be on that page (and isn't currently in the `starter.md` linked above or on the elm-architecture-tutorial pages) is a description of what binaries are installed by the installers and what their roles are for Elm development. Let's wait for a pull request by Gil, then work from there.

**Comment by antonycourtney** [comment]
I also encountered this and [reported it in a post to the mailing list](https://groups.google.com/d/msg/elm-discuss/Y7n8TA7ZlHw/YhGQK_DeAQAJ).

I cloned the repository and took a look through the history. It appears that [the old Get-Started.elm page](https://github.com/elm-lang/elm-lang.org/blob/5b6e0b993784f44399d7db938dd014df625db363/frontend/public/Get-Started.elm) was (accidentally?) removed during a restructuring / cleanup of docs in a [large commit done on Mar. 4](https://github.com/elm-lang/elm-lang.org/commit/5e88c5d622441e34544c6b26f38d0ed0c3b266d4) to "Remove all non-essential pages". 
 
I agree with @jvoigtlaender that [Gil Mizrahi's blog post](http://www.gilmi.xyz/post/2015/07/04/starting-elm) is probably a better starting point for a Getting Started page.

@soupi : Are you up for submitting a PR for a new Getting Started page based on your blog post ? That would be super helpful to newcomers.

**Comment by soupi** [comment]
@antonycourtney : sure. though as I told @jvoigtlaender  I will only be able to start working on this next week. In the meantime I have created a gist with the content of my blog post in markdown format ([here](https://gist.github.com/soupi/6df9d17d84a280a01cf3)). If you have any comments or suggestions feel free.

**Comment by soupi** [comment]
I have updated the [gist](https://gist.github.com/soupi/6df9d17d84a280a01cf3) and created an [elm file](https://gist.github.com/soupi/4b3dcc70074f349ce188) for the getting started page but haven't managed to get elm-website to compile yet so I could test it. Please review the document if you can. feedback is very much appreciated.

**Comment by jvoigtlaender** [comment]
Looks good! I spotted a few typos and would make a few suggestions for local changes. Maybe the easiest way to organize this is that you open a pull request against this repo, including that elm file in an appropriate location. I could then make pull requests against yours and you can incorporate as you see fit. I think I can also help (again by suggesting patches to a pull request opened by you) with integrating this into the website.

**Comment by soupi** [comment]
Alright, I'll try building the website again today (maybe with the beta no-reinstall cabal) and submit a pull request.

**Comment by jvoigtlaender** [comment]
I'm closing this issue, since it has been resolved by #370. Thanks, @soupi!
