### ISSUE TITLE
"Core language" guide references undefined function "double"

### ISSUE THREAD

**Issue by sindikat** [elm-lang/elm-lang.org#329]
1. On page http://elm-lang.org/guide/core-language there is this code snippet:

    > List.map double numbers
    [2,8,6,4]

 When I try to use function `double`, REPL says:

    Cannot find variable `double`

    3|   List.map double [1,2,3,4]
                  ^^^^^^

 This might confuse newbies, so please define this function somewhere or make note. Thanks!

2. Also later the code mentions `String`, which is not imported by default:

    > goodName name = \
    |   if String.length name <= 20 \
    |     then (True, "name accepted!") \
    |     else (False, "name was too long; please limit it to 20 characters")

3. Please change `Number` to `number` in the binary tree example:

 https://github.com/elm-lang/elm-lang.org/blob/master/src/examples/binary-tree.elm#L90

4. http://elm-lang.org/blog/announce/0.12.3 shows the below instead of an actual article:

        Need to display 3D examples!
      
      
        Open the developer console for more details.

5. http://elm-lang.org/blog references blog-posts, however http://elm-lang.org/blog/escape-from-callback-hell is 404

**Comment by jvoigtlaender** [comment]
The 4th point seems to be related to https://github.com/elm-lang/elm-lang.org/issues/209.

Generally, the points here are broader, and more urgent I think, than the current issue title suggests. Maybe change the title to give this issue relevant importance?

**Comment by gabrielf** [comment]
1) The function `double` is defined right before it is used. This may have been fixed after you filed the issue but it's not an issue anymore.

2) The example now includes "import String"

**Comment by evancz** [comment]
I'm not 100% on what is fixed and what is not. Many are fixed though, so I am going to close this.

If any are missing, please open them up as individual issues with a descriptive title.
