### ISSUE TITLE
Source images not showing up in crate, thwomp & first person examples

### ISSUE THREAD

**Issue by alexiamcdonald** [elm-lang/elm-lang.org#330]
Crate, Thwomp and First Person all appear to have errors with their source images.

- http://elm-lang.org/examples/crate
- http://elm-lang.org/examples/thwomp
- http://elm-lang.org/examples/first-person

It happens in Firefox and Chrome. I took screenshots of what appears in the console.

![thwomp](https://cloud.githubusercontent.com/assets/8427242/8699760/2814d41e-2b4b-11e5-9473-4ef3f8e75c04.JPG)

![woodcrate](https://cloud.githubusercontent.com/assets/8427242/8699767/2d383652-2b4b-11e5-8e1d-c0e80b27140d.JPG)

**Comment by raine** [comment]
Same issue with http://elm-lang.org/examples/resize-paint

http://elm-lang.org/paint.jpg

**Comment by evancz** [comment]
Thanks for the report @alexiamcdonald! I think this is a recent development, not sure the root yet.

@raine, this one is just a bad link, should be fixed now. Thanks for pointing it out!

**Comment by alexiamcdonald** [comment]
@evancz yeah, it's definitely a recent development.

The console is actually helping me find the problem now for some reason (yay!)

![thwompresults](https://cloud.githubusercontent.com/assets/8427242/8866841/7ff03146-3204-11e5-954e-81b893a51dfe.JPG)

![thwompresult](https://cloud.githubusercontent.com/assets/8427242/8866860/f15bd65a-3204-11e5-86c6-7fb22503ae2b.JPG)

- http://elm-lang.org/examples/thwomp/result

Console says the problem for thwomp example is from line 12439 in result:

```elm
req.send();
```

Also, I was reading up on similar console errors of this type on stackoverflow somewhere and it said to make sure you have your adblocker off because sometimes it can interfere finding the problem. Not sure how much of that is true in this case but just a good idea just in case.

**Comment by evancz** [comment]
I wonder if it is related to #304?

If you take the code located at the following address in chrome (view-source:http://elm-lang.org/examples/thwomp/result) and make the modifications from #304 and run it locally, does stuff still mess up?

I have been holding off on doing a new release of core because it is a major version bump even though there are no real breaking changes. It's more that 0.15.1 made it way easier to catch errors in docs and exports, so we found a bunch of hidden things escaping. In any case, this might be a good kick to do it anyway.

**Comment by evancz** [comment]
It could also be from a new release of elm-webgl. I recently updated all the packages used on elm-lang.org, so if elm-webgl has been bumped perhaps it introduced the issue.

**Comment by dnalot** [comment]
I'm clearly getting a timeout in Safari too. The WebGL [code responsible](https://github.com/johnpmayer/elm-webgl/blob/3.0.0/src/Native/WebGL.js#L31-L38) is clearly following [spec recommendation](https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API/Tutorial/Using_textures_in_WebGL#Loading_textures). When I manually enter the exact logic in the developer console it loads successfully. On the next refresh it's even cached.

**Comment by dnalot** [comment]
I failed to notice it's in fact using a different implementation based on XHR in Elm Try.

**Comment by dnalot** [comment]
I failed to notice Elm Try is in fact using a different implementation based on XHR. The new code is more flexible but sets a timeout of 30ms. I suspect it's simply too quick. @johnpmayer?

**Comment by evancz** [comment]
@dnalot pointed out the specific location [here](https://groups.google.com/forum/#!topic/elm-discuss/5PjXsXWK5FE). The code causing issues is this:

```javascript
function loadTexture(url) {
    return Task.asyncFunction(function(callback) {
      var req = new XMLHttpRequest;
      req.addEventListener('error', function() {
        return callback(Task.fail({ ctor: 'NetworkError' }));
      });
      req.addEventListener('timeout', function() {
        return callback(Task.fail({ ctor: 'Timeout' }));
      });
      req.addEventListener('load', function() {
        return callback(Task.succeed(toTexture(req)));
      });
      req.open('get', url, true);
      req.timeout = 30;
      req.responseType = 'blob';
      req.send();
    });
  }
```

It looks like [the relevant elm-webgl code](https://github.com/johnpmayer/elm-webgl/blob/856ff04614c81a43dc522140469b5dcc2e294c75/src/Native/WebGL.js#L29-L40) has been updated to not have that timeout anymore. Probably just need to update versions.

**Comment by evancz** [comment]
Alright, all the examples are fixed for me!

Thanks @alexiamcdonald for the report! Thanks @dnalot for finding the exact files and line numbers causing things, that made it super easy to figure out!

**Comment by dnalot** [comment]
The XHR code looked newer than the `Image` code. The timeout is probably even a good idea. I suspect the reasoning was to load it inside a single frame? A full second might ought to be permitted. In any case CC @johnpmayer in case XHR gets re-published.
