### ISSUE TITLE
Syntax Does Not Explain << and >>

### ISSUE THREAD

**Issue by defndaines** [elm-lang/elm-lang.org#333]
Please add an explanation of the `<<` and `>>` operators on the Syntax page.

I see `<<` used in the Todo.elm example, but I didn't find an explanation of the operator on the Syntax page.

**Comment by pdamoc** [comment]
They are explained in the [documentation of Basics](http://package.elm-lang.org/packages/elm-lang/core/2.1.0/Basics#<<)

**Comment by defndaines** [comment]
I think my point was that when you come in through elm-lang.org as a beginner, it isn't immediately obvious that you need to go into the package documentation (and which package documentation?) to figure out what this syntax means. The first time I searched for the meaning, I ended up in the source code for Elm before I found the definition. Since these operators are special and used in the tutorials, it is probably worth calling out on its own on the [Syntax](http://elm-lang.org/docs/syntax) page.

**Comment by jvoigtlaender** [comment]
Well, "these operators are special" is a bit unclear. They are not really special, they are just library definitions. Like other functions in `Basics` are not special, but could be defined by any programmer in their own library as well.

But yes, you are not the first person with that documentation request. (I remember people on the mailing list or in GitHub issues arguing that even though `<<` and `>>` are library operators, and not syntax, it would make sense to explain them on the Syntax page.)

Maybe create a pull request with how/where you would want to see them explained? That might increase the chance of such explanation ending up on the website.

**Comment by jvoigtlaender** [comment]
Just as another data point / someone expecting these operators to be explained on the Syntax page: https://groups.google.com/d/msg/elm-discuss/pmZTYWx5K6w/g97lecLvDQAJ

The proper source place to add such explanation would be here: https://github.com/elm-lang/elm-lang.org/blob/master/src/pages/docs/syntax.elm#L214-L233

**Comment by jvoigtlaender** [comment]
I've made a pull request addressing this: https://github.com/elm-lang/elm-lang.org/pull/383.

**Comment by jvoigtlaender** [comment]
Close this issue since #383 was merged?

**Comment by evancz** [comment]
Thanks @jvoigtlaender!

**Comment by defndaines** [comment]
Thanks @jvoigtlaender ! (I had hoped to put together a PR, but have been out of town.)
