### ISSUE TITLE
Confusing sentence in http://elm-lang.org/guide/reactivity

### ISSUE THREAD

**Issue by akeeton** [elm-lang/elm-lang.org#336]
https://github.com/elm-lang/elm-lang.org/blame/master/src/guide/chapters/reactivity.md#L106

> This exposes the `TaskTutorial` module which has [a friendly values][task-tutorial] that will help build a foundation for working with tasks.

**Comment by jvoigtlaender** [comment]
Indeed, that's a strange sentence.The "a friendly values" phrase could meaningfully be replaced by "a few values" or "a few friendly tasks" or something like that.
