### ISSUE TITLE
Broken links in http://elm-lang.org/blog/interactive-programming

### ISSUE THREAD

**Issue by tomekwi** [elm-lang/elm-lang.org#337]
Hi, as you advised in http://elm-lang.org/blog/interactive-programming I wanted to mess around with examples. So I tried clicking the links:

* http://elm-lang.org/edit/examples/Intermediate/Mario.elm
* http://elm-lang.org/edit/examples/Intermediate/Bounce.elm
* http://elm-lang.org/examples/Intermediate.elm

…but instead of examples I encountered a witty limerick.

Though I have to admit that was fun too :)

**Comment by jvoigtlaender** [comment]
The first of those three links could be replaced by http://elm-lang.org/examples/mario, and the third one by http://elm-lang.org/examples.

I don't know whether the example corresponding to the second of the three links does even still exist on the website.

But what is really a bit embarrassing is the big "404 iframe" inside http://elm-lang.org/blog/interactive-programming that should apparently show a live-editable-and-hotswappable version of that (not anymore existing?) bouncing ball example.

**Comment by jvoigtlaender** [comment]
This issue can be closed. It is covered now by the more comprehensive issue https://github.com/elm-lang/elm-lang.org/issues/450.

**Comment by tomekwi** [comment]
:+1:
