### ISSUE TITLE
Right-click processed by Mouse "Presses" basic example

### ISSUE THREAD

**Issue by ecyrb** [elm-lang/elm-lang.org#34]
When I press right-click on the demo [1], the context-menu pops up and the boolean value stays 'True' until the next left mouse-click.  Chrome Version 27.0.1453.81 beta on 32-bit Ubuntu 12.10.

[1]  http://elm-lang.org/edit/examples/Reactive/IsDown.elm

**Comment by evancz** [comment]
This is caused by an underlying issue in elm-lang/core, so follow along at https://github.com/elm-lang/core/issues/43 for the fix.
