### ISSUE TITLE
Use proper Elm highlighting

### ISSUE THREAD

**Issue by jvoigtlaender** [elm-lang/elm-lang.org#342]
Version 8.7 of https://highlightjs.org/ has been released. It now includes correct Elm highlighting (per [this pull request](https://github.com/isagalaev/highlight.js/pull/868)). So it would be good to replace that asset here by a new version. Then, uses of the `haskell` tag should be replaced by the `elm` tag throughout this repository, except where indeed Haskell code is shown. (Currently, Haskell highlighting is used for Elm code, which is imperfect, since not all the keywords agree between the two languages. Using version 8.7 of the library and replacing `haskell` by `elm` tags would fix that.)

**Comment by evancz** [comment]
[This file](https://github.com/elm-lang/elm-lang.org/blob/master/resources/highlight/highlight.pack.js) should need the same changes as described in https://github.com/elm-lang/package.elm-lang.org/issues/56
