### ISSUE TITLE
Request: Package docs should have a summary at top

### ISSUE THREAD

**Issue by akeeton** [elm-lang/elm-lang.org#345]
The summary would contain the names and type signatures of the functions and types that are documented.

This would make it easier to find a function that you know exists but you don't know the name of.  Also, often you just need to see a function's type without needing to see the full docs.

For example, I knew `List` had the function `intersperse` but I couldn't remember the name.  To find it I had to scan most of the page.

**Comment by evancz** [comment]
Thanks for the request! Can you put this on the package.elm-lang.org repo instead?
