### ISSUE TITLE
Escape from Callback Hell link 404s

### ISSUE THREAD

**Issue by MaxGabriel** [elm-lang/elm-lang.org#348]
The [blog page](http://elm-lang.org/blog) links to a blog post titled ["Escape from Callback Hell"](http://elm-lang.org/blog/escape-from-callback-hell), but this link 404s.

**Comment by flip111** [comment]
related https://groups.google.com/forum/#!topic/elm-discuss/iJPlrvFmtnw

**Comment by jvoigtlaender** [comment]
Another link to that article that should exist according to https://github.com/elm-lang/elm-lang.org/blob/master/src/backend/Router.hs#L184, but doesn't, is http://elm-lang.org/learn/escape-from-callback-hell.

**Comment by Dobiasd** [comment]
In case the content is gone completely, perhaps one could recover [the latest version](https://web.archive.org/web/20150410053637/http://elm-lang.org/learn/Escape-from-Callback-Hell.elm) from [web.archive.org](https://web.archive.org/web/*/http://elm-lang.org/learn/Escape-from-Callback-Hell.elm).

**Comment by evancz** [comment]
Mentioned in the larger "broken links" issue #450
