### ISSUE TITLE
Record update requires an unqualified record name

### ISSUE THREAD

**Issue by mikedamay** [elm-lang/elm-lang.org#349]
{ Graphics.Collage.defaultLine | color <- Color.darkGray } gets the following message:

SYNTAX PROBLEM
jump to error

I ran into something unexpected when parsing your code!
34|   { Graphics.Collage.defaultLine | color <- Color.darkGray }

I am looking for one of the following things:

    a closing bracket '}'
    a lower case name
    whitespace

Elm : fabulous achievement

**Comment by evancz** [comment]
A bunch of folks have run into this, but there are a number of open questions about exactly how to allow this. We have some issues open about changing record syntax and a bunch of mailing list discussions of exactly this, so I am going to close this as a known, but unresolved issue.

Thanks for the report!
