### ISSUE TITLE
No RSS feed for blog

### ISSUE THREAD

**Issue by gampleman** [elm-lang/elm-lang.org#353]
I tried subscribing to the blog, but there seems to be no RSS feed, which makes following posts quite difficult.

**Comment by ni-ko-o-kin** [comment]
+1

**Comment by Anks** [comment]
:+1: This would be great

In the meanwhile, I've rigged up a couple of feeds with [Kimono Labs](https://www.kimonolabs.com) as a workaround:

- [Articles](https://www.kimonolabs.com/api/rss/375r3jxi)
- [Release notes](https://www.kimonolabs.com/api/rss/citre8do)

**Comment by ni-ko-o-kin** [comment]
@Anks 
they don't work anymore

**Comment by user453584** [comment]
+:100: What is the point of a blog without an RSS feed?

**Comment by evancz** [comment]
Someone make a PR that implements this and we can have one! I'd like to have this too, but it can't do itself!

**Comment by evancz** [comment]
I don't know how to make this happen, and the maintenance burden seems like it'll be high if it is made to fit with the existing backend. Let's add this to https://github.com/elm-lang/projects
