### ISSUE TITLE
Texture example has the wrong url for the texture

### ISSUE THREAD

**Issue by pdamoc** [elm-lang/elm-lang.org#354]
is 
`/stripes.jpg`
should be 
`/imgs/stripes.jpg`

**Comment by jvoigtlaender** [comment]
Make a pull request? :-)

https://github.com/elm-lang/elm-lang.org/blob/master/src/examples/texture.elm

**Comment by pdamoc** [comment]
Oops.... I think I did something very silly. 
This is my first pull request and I think I might have merge it into the official repository. 
I thought I was merging it into my own fork. 

Strange that I could do that.

**Comment by jvoigtlaender** [comment]
Looks like you have succeeded (https://github.com/elm-lang/elm-lang.org/pull/355)!

Then you can close this issue here (since it is addressed by the pull request).

**Comment by pdamoc** [comment]
Thank you!
