### ISSUE TITLE
Add timestamp/hash to everything.js to invalidate cached versions

### ISSUE THREAD

**Issue by dela3499** [elm-lang/elm-lang.org#357]
See [this thread](https://groups.google.com/forum/#!topic/elm-discuss/ZV33-IcT6l4) for context. 

When using Try Elm after everything.js has been changed, you may be using a cached version instead of the latest version, which may cause an error in compilation. To avoid this, a timestamp or hash should be added to the filename (and associated script import statement). 

The filename is set [here](https://github.com/elm-lang/elm-lang.org/blob/12d97c8876e14a0e33780459ac6d707d14c2bc72/src/backend/Init/Compiler.hs#L120) and the import statement is created [here](https://github.com/elm-lang/elm-lang.org/blob/6341dcde66de43c8ccb2b345f0027b3df4df9da2/src/backend/Generate.hs#L67).

It should be straightforward to add a timestamp or hash when saving everything.js, but it's less clear how to create the script import statement. 

There are at least two approaches: 
1. Check the filesystem for a file with 'everything' in the name, and use this for the import. 
2. Pass around the timestamp/hash within the context of the running program. (i.e. create the timestamp, then pass it as an argument to the functions that create and import everything.js)

**Comment by dela3499** [comment]
For the latter option, it looks like you could generate a timestamp in Main.hs and pass it where it's needed. 

This would result in 9 separate changes - One to create the timestamp in Main.hs, and one change for each of the 8 locations below. 

It look like you'd need to pass the argument through these functions to when creating the file itself. 
Compiler.getInterfaces
Compiler.init
Main.main

And do the same when creating the import statement. 
Generate.scripts
Generate.userHtml
Router.compile
Router.router
Main.main

**Comment by evancz** [comment]
No longer uses `everything.js`
