### ISSUE TITLE
Broken links in "syntax" page

### ISSUE THREAD

**Issue by amitaibu** [elm-lang/elm-lang.org#363]
http://elm-lang.org/docs/syntax

Note sure where they need to redirect

![elm_syntax](https://cloud.githubusercontent.com/assets/125707/9395758/f011730a-4798-11e5-9aca-6527a97a55f3.jpg)

**Comment by jvoigtlaender** [comment]
These examples have simply disappeared, I think.

**Comment by evancz** [comment]
Yeah, those examples went away with the website redo. Probably want to just remove the links for now?

**Comment by jvoigtlaender** [comment]
Done in https://github.com/elm-lang/elm-lang.org/pull/364.

**Comment by evancz** [comment]
Just updated the site, should be fixed thanks to @jvoigtlaender!

**Comment by jvoigtlaender** [comment]
So, @amitaibu, ready to close this issue?
