### ISSUE TITLE
Fix code examples in Reactivity page

### ISSUE THREAD

**Issue by amitaibu** [elm-lang/elm-lang.org#367]
Currently one cannot copy/ paste the code examples - as they are missing some info.

I have started a [gist](https://gist.github.com/amitaibu/bd130e24e586167ef92e) with the fixes, I'll turn to PR once I go over all the code examples, or maybe better to create a working repo with the different example files?

**Comment by evancz** [comment]
I like the approach you are currently using. I am planning to write a section of the guide called "Error Handling" that might build a better foundation for all this stuff, so I think it makes sense to do it your way for now. We can revisit this after the guide shifts around more.

I'm closing so we can just track the PR you made. Let's open a new thing depending on how things go!

**Comment by amitaibu** [comment]
:+1:
