### ISSUE TITLE
No license?

### ISSUE THREAD

**Issue by bkaestner** [elm-lang/elm-lang.org#380]
It's not obvious whether elm available under a free license. A [short search](https://www.google.de/search?q=license+site:elm-lang.org) yields a single blog post, which mentions that it "is still totally open source under the BSD3 license".

Given that the blog post is more than 2 years old, it's not really easy to find by hand. Alternatively one needs to find the elm repositories (which also aren't linked on the page) and check the licence files manually.

So an additional feature or notice on the main page would be great. A link to the [elm-plattform](https://github.com/elm-lang/elm-platform) would also help tremendously:

> ## It's free!
> Not sure whether to invest your money yet? Lucky you! The [elm-platform](https://github.com/elm-lang/elm-platform) and all its components are available under a BSD-3 license.

**Comment by evancz** [comment]
All of the repos in the @elm-lang organization have a LICENSE file that is BSD3, like [this one](https://github.com/elm-lang/elm-lang.org/blob/master/LICENSE). I don't know what specific thing you want in addition to this, so I am going to close. If you have a specific suggestion I can maybe do more.

**Comment by bkaestner** [comment]
@evancz Sure, all GitHub repository have a LICENCE file. But there's no mention of the licence on [elm-lang.org](http://elm-lang.org) itself.

**Comment by evancz** [comment]
Ah, I get it. That used to be in the footer of the page, but I did a revamp and never got a chance to add the footer back. I'll open an issue describing that.
