### ISSUE TITLE
read documentation offline

### ISSUE THREAD

**Issue by flip111** [elm-lang/elm-lang.org#381]
What is the best way to read the documentation offline? I tried downloading them with httrack but that didn't work (some javascript error).

**Comment by jvoigtlaender** [comment]
Maybe what's discussed in [this thread](https://groups.google.com/d/msg/elm-discuss/k5E7x3McYwM/btHGxwa3CgAJ) is a good option for you?

**Comment by evancz** [comment]
I don't think we can resolve this on this repo, so I'm going to close this thread.

I recall someone on elm-discuss announcing a docs previewer. And there are some issues open to get the raw JSON docs to download automatically on install. And this project is already requested [here](https://github.com/elm-lang/projects#improve-elm-reactor-navigation-page)?

**Comment by flip111** [comment]
Looks good guys, thank you

**Comment by DanielSokil** [comment]
`wget -m http://elm-lang.org/docs` (;
