### ISSUE TITLE
minor issue in http docs

### ISSUE THREAD

**Issue by flip111** [elm-lang/elm-lang.org#400]
http://package.elm-lang.org/packages/evancz/elm-http/2.0.0/Http

`import Json.Decode (list, string)` compiler warns about forgetting `exposing` before `(list, string)`

**Comment by evancz** [comment]
Can you do a pull request to evancz/elm-http to fix it in the latest version?

Or if you think it should be fixed by hand, I can do that. If so, open an issue at https://github.com/elm-lang/package.elm-lang.org/
