### ISSUE TITLE
"Model the Problem" code issue

### ISSUE THREAD

**Issue by CWelshE** [elm-lang/elm-lang.org#410]
There are sections of Elm code in [this](http://elm-lang.org/guide/model-the-problem) article that do not actually compile. For example:

```elm
import List exposing (sum, map, length)


averageNameLength : List String -> Float
averageNameLength names =
  sum (map String.length names) / length names
```
Attempting to compile this code "as-is" will result in the following compilation error due to not importing `String`:
```
Cannot find variable `String.length`.
5|   sum (map String.length names) / length names

The qualifier `String` is not in scope. 
```
Importing `String`, however, does not completely solve the issue; we're then presented with errors relating to mismatched types (because we want a `Float`):
```
The right argument of (/) is causing a type mismatch.
6|   sum (map String.length names) / length names

As I infer the type of values flowing through your program, I see a conflict
between these two types:

    Float

    Int

The left argument of (/) is causing a type mismatch.
6|   sum (map String.length names) / length names

As I infer the type of values flowing through your program, I see a conflict
between these two types:

    Float

    Int
```
In this case, the problem appears to be that `String.length` and `List.length` return an `Int`.

It is probably not the ideal solution, but this is one way of fixing it:
```elm
import List exposing (sum, map, length)
import String

stringLengthFloat : String -> Float
stringLengthFloat string =
  toFloat(String.length string)
  
listLengthFloat : List String -> Float
listLengthFloat list =
  toFloat(List.length list)

averageNameLength : List String -> Float
averageNameLength names =
  sum (map stringLengthFloat names) / listLengthFloat names
```
Alternatively, you may also convert both sides of the expression to a `Float`:
```elm
import List exposing (sum, map, length)
import String

averageNameLength : List String -> Float
averageNameLength names =
  toFloat(sum (map String.length names)) / toFloat(length names)
```
I think there's probably a better way, though, so I thought I'd register a new issue and find out.

**Comment by jvoigtlaender** [comment]
See https://github.com/elm-lang/elm-lang.org/pull/377 and https://github.com/elm-lang/elm-lang.org/pull/386 and https://github.com/elm-lang/elm-lang.org/pull/393.

**Comment by CWelshE** [comment]
Apparently, I forgot to search!
