### ISSUE TITLE
Get more developers interested from the start - Improve the homepage

### ISSUE THREAD

**Issue by sbrink** [elm-lang/elm-lang.org#422]
I just saw Evan's presentation about from the Curry on talk.
As a programmer myself I know hard it is to switch between technical
and marketing stuff. Is any help for marketing appreciated?

I think the developers are more interested what's in it for them.
Maybe it's a good idea to translate the features to benefits.

If I use the iPod slogan as comparision - the current homepage sounds
more like "2 GB hard drive" instead of Apple's "300 songs in your pocket".

Maybe we could translate the features to meaningful things for the developer.

Here are you some ideas how to translate them:
## Less time debugging

What's the worst about coding? - Debugging. It's time-wasting, it's frustrating,
it let's you having a bad day. The elm compiler prevents 8 in 10 of the most 
stupid developer mistakes. How?

Learn more >
## Enjoy snappy websites

Most of the time performance is not a concern. But in the rare situations when
performance is important, it's good to have a [insert good english idiom for comparision here :)].
Wanna know how fast elm is?

Learn more >
## Upgrades with confidence

Ever upgraded a library from eg. 1.0.3 to 1.0.4 and thought it's easy - only to find some
breaking api changes. That's thing of the past. Elm compares the apis during the submission
and rejects wrongs numbering. Impossible?

Learn more >
## Faster readable code

You read more code than you write. If a programmer writes 7 new lines a day you sure read a hello lot
more code than that. Today attention is a rare good. Conclusion - your language's syntax should not distract you. Elm is minimalistic. How does Elm prevent unnecessary noise?

Learn more > 
## Some of the hard features included

Some features help the user experience tremendously. E.g. an undo function. Your users should be allowed to make mistakes (and they'll do). It's normally a hard thing to do. In Elm you could see a part of the language. What else is possible?

Learn more >
## Don't feel guilty about NOT testing anymore

Testing is hard in the non-functional world. Do you know about mocks, stubs, spies, whatever? These are things you don't need to know in Elm. If everything is a stateless function writing tests is no-brainer.
Wanna know how easing testing is in Elm?

Learn more >

The "Learn more >" links would lead to more information about the subject.

If we track the links we could learn more about what the developers are interested in.

Any suggestions, ideas, thoughts are welcome :)

**Comment by rofrol** [comment]
:+1:

**Comment by tullo** [comment]
:+1:

**Comment by willnwhite** [comment]
I remember Evan saying how he couldn't think of a good way to explain "safe", as in type safety. When I'm programming in JavaScript, it let's me do things I shouldn't, like use an array with undefined elements, that'll haunt you later. Elm doesn't let you do things that will haunt you (bite you in the arse).

**Comment by willnwhite** [comment]
Upfront errors: no errors waiting to happen. Rather than "no runtime errors", because I remember not knowing what runtime means.

**Comment by willnwhite** [comment]
"No null, no undefined." Both awful to have to get your head around.

**Comment by willnwhite** [comment]
The compiler messages are like having the language designer help you build your project.

**Comment by willnwhite** [comment]
`List.head []`as a concrete example of no runtime errors, compared with even Haskell.

**Comment by willnwhite** [comment]
``` elm 
type alias Model =
    { things : Maybe (List Thing)
    }
```
as a concrete example of Elm helping you to build your UI properly (see http://blog.jenkster.com/2016/06/how-elm-slays-a-ui-antipattern.html).

**Comment by evancz** [comment]
I try to curate the messaging myself, but I think the root idea here makes a ton of sense.

That said, this is too many things in one issue. I think the bullets on the current home page do a pretty good job of translating technical details into useful information, without going so far as to become vague and marketing-y. If you think there are specific ones on the current page that should change, it makes sense to talk about them one at a time.
