### ISSUE TITLE
Some pages in /blog/ are broken.

### ISSUE THREAD

**Issue by dram** [elm-lang/elm-lang.org#431]
Following pages in /blog are broken:

* http://elm-lang.org/blog/announce/0.12

with error:

```
Ran into a `Debug.crash` in module `Main` on line 40

    The message provided by the code author is:
   
        need to show examples

Open the developer console for more details.
```

* http://elm-lang.org/blog/announce/0.12.3

with error:

```
Ran into a `Debug.crash` in module `Main` on line 75

    The message provided by the code author is:
   
        Need to display 3D examples!

Open the developer console for more details.
```

**Comment by jvoigtlaender** [comment]
Already noted in https://github.com/elm-lang/elm-lang.org/issues/209. Close as a duplicate here?

**Comment by dram** [comment]
I thought this bug was introduced in Elm 0.16.0, please close.

**Comment by jvoigtlaender** [comment]
I don't have the power to close this. You have.

**Comment by dram** [comment]
Find the button, thanks. :D
