### ISSUE TITLE
Install page inaccuracy

### ISSUE THREAD

**Issue by jvoigtlaender** [elm-lang/elm-lang.org#435]
The page says:

"To upgrade to a newer version of Elm, run the installer again. They safely overwrite old executables so your machine is in a consistent state."

That's not true of the Windows installer. It does not overwrite old executables, it just changes the path to point to the new executables. It is also not true of the `npm` installer, I think. It might or might not be true of the Mac installer.

**Comment by jvoigtlaender** [comment]
It's also not clear to me now what "The Windows installer comes bundled with an uninstall option." means. Will the uninstaller remove Elm completely? Or will it remove one Elm version? Will the previously (presumably older) Elm version become usable (accessible on path) again?

**Comment by evancz** [comment]
What is the confusion here?

The windows installer puts things in `ProgramFiles/Elm-Platform/*/` where `*` is the version. In that folder is an uninstaller that'll remove that version.

What's the point of this issue though? Has someone been tripped up in a particular way? If not, let's close this.

**Comment by jvoigtlaender** [comment]
See https://github.com/elm-lang/elm-reactor/issues/157#issuecomment-160323227.

**Comment by evancz** [comment]
So he thought the wrong thing, but what was the consequence exactly? I need you to turn confusion into a concrete action. What should be done to turn this into a PR?

**Comment by jvoigtlaender** [comment]
Will think about this.

**Comment by jvoigtlaender** [comment]
So here is why I think the text "To upgrade to a newer version of Elm, run the installer again. They safely overwrite old executables so your machine is in a consistent state." on http://elm-lang.org/install should change:

It is factually wrong. The windows installer does not overwrite old executables. And some people are sensitive (for security or other concerns) about what exectuables are or are not on their computers. So if you tell them "installing Elm 0.16 will make sure that there are no Elm 0.15 executables on your machine anymore" and they find that that statement is not true, by encountering the Elm 0.15 executables still on the machine, they will feel uncomfortable/cheated. "What else of what is written on that site should I believe or not believe?"

I propose to change the second sentence into "They displace old executables so your machine is in a consistent state." That formulation covers both:
* actually overwriting executables,
* changing paths so that old executables are not found anymore,

so it is true to all the different installers' behaviors.
