### ISSUE TITLE
Something odd with type annotation in the binary tree examples.

### ISSUE THREAD

**Issue by Hobinx** [elm-lang/elm-lang.org#441]
Correct me if I'm wrong, because I'm just a beginner in programming, not very sure about this problem.
In the exercises of the binary tree examples, the fold function has a type signature: `fold : (a -> b -> b) -> b -> Tree a -> b`, and I implement it like this:
```Elm
fold f e tree = 
  case tree of
    Empty -> e
    Node v left right ->
      f v (fold f e left) (fold f e right)
```
Does the type signature should be: `fold : (a -> b -> b -> b) -> b -> Tree a -> b`?

**Comment by evancz** [comment]
I think that's the type of the thing you wrote in particular, not the type of `fold` that the exercise is looking for though.

Here's a hint: Calling `fold` *requires* an accumulated result and also *produces* an accumulated result. There are many ways to put things together based on that.

Hope that helps! If not, try asking on elm-discuss, folks are happy to help more ;)

**Comment by Hobinx** [comment]
Thanks! I will work that out, sorry to bother.

**Comment by evancz** [comment]
If you ever want the secrets, check out https://github.com/evancz/elm-hack-night/tree/master/trees which has the solutions. But try not to look! It's really cool when you realize the solution on your own!

**Comment by Hobinx** [comment]
How nice of you!
