### ISSUE TITLE
elm-lang.org is down.

### ISSUE THREAD

**Issue by alinz** [elm-lang/elm-lang.org#445]
I wanted to read elm docs but the server keeps unavailable. Is there any reason? Does everyone have a clone of website when they try to read the doc? 

Any thoughts and ideas?

**Comment by evancz** [comment]
Should be back, sorry for the trouble. It seems to be going through some growing pains.

**Comment by alinz** [comment]
@evancz, Awesome, big fan of Elm, it's been a month since I started and I have been porting couple of my react apps into elm. It's pretty good. Thanks for very fast response.

**Comment by jvoigtlaender** [comment]
@alinz, a clone is mentioned in [this thread](https://groups.google.com/d/msg/elm-dev/npzSAwj85fQ/jJA9Pa5gCAAJ).

**Comment by alinz** [comment]
@jvoigtlaender thanks!
