### ISSUE TITLE
i could not touch elm-lang.org

### ISSUE THREAD

**Issue by ustuntas** [elm-lang/elm-lang.org#447]
Hi,

I try to connect to elm-lang.org but i could not connect.

What is problem?

Regards,

Ustuntas

**Comment by localshred** [comment]
Same here http://downforeveryoneorjustme.com/elm-lang.org

**Comment by Gee-Bee** [comment]
It's working again.

**Comment by jvoigtlaender** [comment]
@ustuntas, please close this issue.

**Comment by ustuntas** [comment]
I can not log in because of my health problems .. I'm so sorry for closing issue..

**Comment by evancz** [comment]
No worries @ustuntas, thanks for reporting!
