### ISSUE TITLE
Add builtwithelm to community or examples?

### ISSUE THREAD

**Issue by lukewestby** [elm-lang/elm-lang.org#452]
Hi all!

I just wanted to check and see if there was any interest in adding builwithelm.co to the examples or the community page to bring more visibility and get more folks to list their projects. I was planning to submit a PR but I'm not sure where the link best fits in the site and so wanted to defer that decision to all of you as well.

The repo was recently moved to the elm-community org, you can find it here: https://github.com/elm-community/builtwithelm

Let me know what you think, and definitely no big deal if you'd rather not include it on the site. Thanks!

**Comment by evancz** [comment]
I have been wanting to add this as well :)

My plan was to put a link on the home page under the examples. Where else do you think it should go? Putting it on the /examples page makes sense to me. On /docs though?

**Comment by lukewestby** [comment]
My hope was that we could identify it not just as an example but as something that exists for the community in which everyone can participate, and as cool as it would be for me to have my name and project on the home page :wink: I think that purpose wouldn't be communicated effectively if it were in the home page list. Where on /docs do you think it would fit best?

**Comment by lukewestby** [comment]
Looks good on the home page!
