### ISSUE TITLE
Only dummy code for cube and thwomp examples

### ISSUE THREAD

**Issue by jvoigtlaender** [elm-lang/elm-lang.org#462]
The code at http://elm-lang.org/examples/cube currently looks like this:
```elm
x = 32
{--
...
a lot of defunct stuff
...
--}
```

**Comment by evancz** [comment]
Waiting for update to elm-webgl and elm-linear-algebra, and it sounds like they maybe just got updated.

**Comment by jvoigtlaender** [comment]
Also http://elm-lang.org/examples/thwomp.

**Comment by jvoigtlaender** [comment]
The two relevant packages are now available in Elm-0.16 versions: http://package.elm-lang.org/packages/elm-community/elm-linear-algebra/1.0.1/, http://package.elm-lang.org/packages/elm-community/elm-webgl/1.0.0/.
