### ISSUE TITLE
model-the-problem section has possible out of date info

### ISSUE THREAD

**Issue by burnt43** [elm-lang/elm-lang.org#475]
This section of the docs has the following example code

```elm
longestName : List String -> Int
longestName names =
  List.maximum (List.map String.length names)
```

However, using elm 0.16.0 it seem List.maximum returns a Maybe Int not an Int. 

<pre>
-- TYPE MISMATCH ------------------------------------------------------ main.elm

The type annotation for `longestName` does not match its definition.

85│ longestName : List String -> Int
                  ^^^^^^^^^^^^^^^^^^
The type annotation is saying:

    List String -> Int

But I am inferring that the definition has this type:

    List String -> Maybe Int

Detected errors in 1 module.
</pre>

So, it I change it to the following it works.

```elm
longestName : List String -> Maybe Int
```

Also, the paragraph explaining the example probably will need to change because it uses language like "We also say the longestName function is definitely going to return an Int so if we use its result somewhere else, we have a 100% guarantee that it's a whole number.", but that does not seem to be the case anymore.

**Comment by jvoigtlaender** [comment]
See https://github.com/elm-lang/elm-lang.org/pull/442.

**Comment by jvoigtlaender** [comment]
@burnt43, can you close this issue? Or do you see need for anything that is not covered by #442?

**Comment by jvoigtlaender** [comment]
@burnt43, comment please.
