### ISSUE TITLE
Is there a way to add / remove fields from records?

### ISSUE THREAD

**Issue by durkiewicz** [elm-lang/elm-lang.org#514]
There used to be a syntax for adding and removing fields from records in Elm 0.15.

But in 0.16 this code doesn't compile:
```elm
withX = { x = 4 }
withXY = { withX | y = 5 }
```

When you click on 0.16 release notes link, you go to this page: http://elm-lang.org/blog/compilers-as-assistants
And this page still says:
> "Elm uses a very cool record system. It is based on an excellent paper by Daan Leijen that lets you add and remove fields from records, all while keeping the types simple"

This page:
http://elm-lang.org/docs/records
Should definitely be updated.
If Elm 0.16 allows adding / removing fields from records then there should be an info about the syntax.
If it doesn't allow it then the records docs should explicitly say it because it is not intuitive.

**Comment by jvoigtlaender** [comment]
Hmm, in that post, you should continue reading after the two sentences you quote. The next two paragraphs are:
> I added support for this back in 0.7, and at the time, I had never seen a language (with a real working compiler) that allowed field addition and deletion like this. So I had intuition, but no way to get real experience. I worried that it could encourage overly complex code, so from the start I was very conservative, knowing that we could expand or contract the features as we got more data.
> 
> Well it has been more than two years since then, and the results are in. Pretty much no one ever used field addition or deletion. In the few cases where people did use it, it got pretty crazy pretty quickly. The one real-world case I know of is recorded here if you want to see, and the code could be rewritten with union types, which turned out nicer anyway.

So the information that Elm does *not* anymore have what you are asking about could hardly be any more explicit?

About the http://elm-lang.org/docs/records page: What should be updated there? Is it currently mentioning adding/removing fields? If not, then all is fine, because Elm does not have these features.

**Comment by jvoigtlaender** [comment]
@durkiewicz, do you have answers to my questions in the previous comment? If not, please close this issue, because it would seem there is no action be taken here.

**Comment by JordyMoos** [comment]
Mmm to bad I would have liked having it.
