### ISSUE TITLE
Announce Elm 0.12.3 post fails rendering

### ISSUE THREAD

**Issue by doppioslash** [elm-lang/elm-lang.org#516]
http://elm-lang.org/blog/announce/0.12.3 fails with:

Ran into a `Debug.crash` in module `Main` on line 75

    The message provided by the code author is:
    
        Need to display 3D examples!

Open the developer console for more details.

**Comment by jvoigtlaender** [comment]
Known problem. Covered by https://github.com/elm-lang/elm-lang.org/issues/450.

**Comment by jvoigtlaender** [comment]
Close this issue as a duplicate? (See above.)

**Comment by jvoigtlaender** [comment]
@doppioslash, close?
