### ISSUE TITLE
Make "Try" code shareable

### ISSUE THREAD

**Issue by ohanhi** [elm-lang/elm-lang.org#519]
As someone on the Elm Slack said:

> to bad you cant save your fiddles at http://elm-lang.org/try

It would be great if you could share/bookmark the code you've written into http://elm-lang.org/try. We could do this the easy way by reproducing the idea from [babeljs.io/repl/](https://babeljs.io/repl/#?experimental=false&evaluate=true&loose=false&spec=false&code=console.log(%22This%20is%20an%20example.%22)%3B). In essence, we'd need to encode the whole inputted code into the URL and decode that when a user navigates to such a URL.

This way we could have the sharing capability right on Elm-lang.org, without much server-side trouble (like uploading and serving Elm files).

**Comment by jvoigtlaender** [comment]
Just in case you don't know there is an alternative (unfortunately not up to date with Elm 0.16): http://share-elm.com/

**Comment by ohanhi** [comment]
Yes, I know. The main advantages with http://elm-lang.org/try to me are:

- It is the official site of the language, so it's far easier to find
- Should always be up-to-date with the current version of Elm
- You can `import Html` (among others) just like that

**Comment by jvoigtlaender** [comment]
I agree on all points, really. :smile:

**Comment by forresto** [comment]
FWIW, you can also compress code to/from the hash with something like [rawdeflate](https://github.com/forresto/turtle-svg/blob/gh-pages/js/rawdeflate.js), [rawinflate](https://github.com/forresto/turtle-svg/blob/gh-pages/js/rawinflate.js):

``` js
  function decode ( string ) {
    return RawDeflate.inflate( window.atob( string ) )
  }
  function encode ( string ) {
    return window.btoa( RawDeflate.deflate( string ) )
  }
```

**Comment by evancz** [comment]
Agree that this would be cool, but I do not want a new maintenance burden. Best way to make progress is for someone to make a version of the online editor that has these features. If it's all nice and simple, we can merge it in. If not, it's fine too. No need to block or coordinate. Just make it and see!

**Comment by evancz** [comment]
May make sense to add this to https://github.com/elm-lang/projects as well!
