### ISSUE TITLE
Maybe Result's seems not possible?

### ISSUE THREAD

**Issue by TheoAndersen** [elm-lang/elm-lang.org#524]
Hi,

I'm trying to use Maybe and Result together, to specify a type which might have a value, and when it does, it's the output of an operation which might have failed. (as in sometimes we ask for this with the Http library)
As far as i have understood this could be modelled with ´´´Maybe Result String Bool´´´ ex, where the String is an error message and the Bool is the answer.

But it seems the compiler dosen't like this, because the Maybe part of it cannot figure out why the values dosen't always have both the String and Bool in the return type.

I know i can model this myself with specific types, but it would be nice if i could use the core constructs instead.

Am i missing something?

Here is an example which gives the error in the online elm editor.
```
module TestMaybeResult (..) where
import Html exposing (..)


type alias MaybeGivesAResult = Maybe Result String Bool

ditNotAttempt : MaybeGivesAResult
ditNotAttempt = 
  Nothing

gaveAnOkResult : MaybeGivesAResult
gaveAnOkResult = 
  Just (Ok True)
  
woopsFailed : MaybeGivesAResult
woopsFailed = 
  Just (Err "What happened?!")
```

An example error (all the functions fail)
```
TYPE MISMATCH
The type annotation for `gaveAnOkResult` does not match its definition.

11| gaveAnOkResult : MaybeGivesAResult
The type annotation is saying:

    Maybe Result String Bool

But I am inferring that the definition has this type:

    Maybe (Result a Bool)
```

Coming from a c# background i think we would have had to type-cast the value there, but I'm pretty sure this would not be the Elm solution ;)

**Comment by jvoigtlaender** [comment]
Immediate answer: What you want can be modelled as type `Maybe (Result String Bool)`.

BUT: Please don't bring up such questions here. Do it on the mailing list: https://groups.google.com/forum/#!forum/elm-discuss. This issue tracker has a certain purpose, and it's important that it stays focused on that purpose. Answering questions as above is not in that focus.

**Comment by evancz** [comment]
Thanks @jvoigtlaender! Yeah, folks on the mailing list can give a much more in depth answer and they are super friendly :)

**Comment by TheoAndersen** [comment]
Ahh, darn it.. didn't think about the paranthesis.

Thanks for the answer, and sorry. I'll use the mailing list in the future for this kind of questions.
