### ISSUE TITLE
elm-hedley is listed as a "game"

### ISSUE THREAD

**Issue by jvoigtlaender** [elm-lang/elm-lang.org#527]
On http://elm-lang.org/examples, there's a category "Games", in whose subcategory "community" there's a link to https://github.com/Gizra/elm-hedley.

@amitaibu, is elm-hedley really a "game"?

**Comment by amitaibu** [comment]
> @amitaibu, is elm-hedley really a "game"?

No, it's a webapp or SPA. Should we open a new category for it then?

**Comment by jvoigtlaender** [comment]
Yes, that would be better than listing it as a game when it isn't.

**Comment by amitaibu** [comment]
Ok, I'll create a PR

(also happy to see a core dev coming across hedley :wink: )

**Comment by renatomoya** [comment]
Looks like this was resolved, wasn't it? Close?

**Comment by jvoigtlaender** [comment]
@renatomoya, in what sense was this resolved? The application ist still listed as a game, which it isn't.

**Comment by renatomoya** [comment]
@jvoigtlaender Oh, you're right. I thought _Community_ was it's own section.

**Comment by amitaibu** [comment]
This is tackled now in #537
