### ISSUE TITLE
Inconsistent missing right-click events in http://elm-lang.org/examples/mouse-is-down

### ISSUE THREAD

**Issue by MrMormon** [elm-lang/elm-lang.org#533]
I haven't even tried on the machine to know if this is Elm's fault (npm is too sudo-happy), but the behavior of http://elm-lang.org/examples/mouse-is-down is inconsistent between Chrome and Firefox and are both unexpected.

In Chrome, the displayed value stays true while the right-click menu is open.

In Firefox, the displayed value expectedly returns to false.

However, according to the display, both miss right-mouse-button-down to exit the menu. Is there anything Elm should be doing about this?

**Comment by evancz** [comment]
This example no longer exists. I defer to browser vendors to explain what is "the right thing" here. I'm not even sure it's always possible to detect if it is a left or right click.
