### ISSUE TITLE
Old examples disappeared / update Openlayers example

### ISSUE THREAD

**Issue by eddy-geek** [elm-lang/elm-lang.org#536]
I am trying to find an example to interact with an openlayer map, mostly trying to figure out if Elm is a good fit for a complex map-based app.
The closest I got was Map.elm removed in commit https://github.com/elm-lang/elm-compiler/commit/9aa8e3b243a842b590c5111a45b9da7b03336621 "Get rid of the Examples/ directory. Planning on moving it to a separate repo" 3 years ago.

Is there an updated version / is it possible to have it ? There is nothing close currently in http://elm-lang.org/examples

**Comment by evancz** [comment]
If you are looking to do lots of stuff with maps, you will want to use "ports" to talk to whatever mapping library you are using. You can read more about ports at http://guide.elm-lang.org/interop/html.html and http://guide.elm-lang.org/interop/javascript.html
