### ISSUE TITLE
Please add documentation for the build-in ports

### ISSUE THREAD

**Issue by mexx** [elm-lang/elm-lang.org#541]
According to [Runtime.js](https://github.com/elm-lang/core/blob/218bf6b28c9be53f7303a10a1580e25955d44978/src/Native/Runtime.js#L245-L268) the ports named `title` and `redirect` are automagically wired up.
There should be at least a note in the docs about this behavior.

**Comment by jvoigtlaender** [comment]
This is already noted in the docs: http://elm-lang.org/docs/syntax#javascript-ffi

**Comment by mexx** [comment]
Ok, that's great, I haven't found it on http://elm-lang.org/guide/interop. I think a note there might help ;)

**Comment by jvoigtlaender** [comment]
I agree.

**Comment by evancz** [comment]
It doesn't exist anymore.
