### ISSUE TITLE
Example in model-the-problem.md has line of code which wont compile.

### ISSUE THREAD

**Issue by rluiten** [elm-lang/elm-lang.org#547]
In https://github.com/elm-lang/elm-lang.org/blob/master/src/guide/chapters/model-the-problem.md.

Line in example that wont compile is. "String.toInt : String -> Result String Int"

Either comment it out in the example or put it outside the example code block.

**Comment by evancz** [comment]
Should be different now in http://guide.elm-lang.org/types/union_types.html

Thanks for the report!
