### ISSUE TITLE
no where to link to get-started?

### ISSUE THREAD

**Issue by notyy** [elm-lang/elm-lang.org#557]
Hi, I googled elm make, and find http://elm-lang.org/get-started , that is great place for elm tools introduction. 
But from http://elm-lang.org/docs there seems to be no link to get-started page. maybe the link is in some other place I don't know?

**Comment by jvoigtlaender** [comment]
No, there is no such link at present (only one from http://elm-lang.org/install). I have several issues/PRs open to provide better linking to the get-started page, but they remain unprocessed.

**Comment by evancz** [comment]
There's a link now.

**Comment by evancz** [comment]
Oops, maybe not. Will check again.

**Comment by jvoigtlaender** [comment]
There isn't.

**Comment by qleonetti** [comment]
Still no link :) I started learning today and it's not obvious at all Where you should start. Fortunately, the gitbook links to it. It's really confusing to see examples but not obvious explanation of how to run them locally.

**Comment by evancz** [comment]
Okay, now it's on /docs
