### ISSUE TITLE
Elm-Conf

### ISSUE THREAD

**Issue by RubenSandwich** [elm-lang/elm-lang.org#558]
I recently noticed that for Strange Loop 2016 there will be a mini one day [Elm-Conf](http://www.thestrangeloop.com/preconf.html).

Considering that Strange Loop registration is opening up soon, it would be helpful to draw some attention to it. Maybe a blog post or something? Perhaps the community already planned something and I just found it before the announcement by accident, but it'd be great to advertise it on the official Elm Blog.

**Comment by evancz** [comment]
Will do!
