### ISSUE TITLE
404 in your online docs

### ISSUE THREAD

**Issue by gsklee** [elm-lang/elm-lang.org#563]
http://elm-lang.org/guide/interop

Not very ideal to have your online docs broken when you hit the front page of Hacker News! 😉

**Comment by evancz** [comment]
Where are you finding this link? Some folks were seeing a cached page of /docs and I think that's what happened to you. Can you reopen this with more information if the link exists after a hard refresh of the page?

**Comment by jvoigtlaender** [comment]
There's plenty of places on http://elm-lang.org/ that still link to `/guide/interop`. For example all the places in pull request https://github.com/elm-lang/elm-lang.org/pull/501/.

Just one specific example: the "ports" link in http://elm-lang.org/blog/announce/0.11.

**Comment by gsklee** [comment]
I found it through [an action](https://www.google.com.tw/search?q=elm+interop&oq=elm+interop&aqs=chrome..69i57j69i60j0j69i60.250j0j7&sourceid=chrome&ie=UTF-8) most inquisitive developers will do when they see yet another compile-to-JS something.

**Comment by jvoigtlaender** [comment]
https://github.com/elm-lang/elm-lang.org/pull/567 will directly address this case and a few others.
