### ISSUE TITLE
Package Management details on Getting Started page

### ISSUE THREAD

**Issue by matthewoden** [elm-lang/elm-lang.org#571]
We were discussing on-boarding in elm-slack, and it was brought up that the elm-package manger section could be a little more explicit.

Specifically, the package name structure is inferred, rather than explicitly stated. It might be good to highlight the structure of `user/package` `version`.

Carrying on with this idea - having explicit installation instructions for each package on the elm-package page itself might be a nice touch. (I don't know if elm-lang.org is the right place for this, or if I should move this to `elm-lang/elm-package`.)

The `elm-package.json` description also trails off with an ‘etc’, which implies that there’s more, but additional options don't seem to be fleshed out anywhere. Is there more?

**Comment by evancz** [comment]
I think it makes sense to consolidate this into https://github.com/elm-lang/package.elm-lang.org/issues/27
