### ISSUE TITLE
Upgrade to highlight.js version with syntax definition for Elm 0.17

### ISSUE THREAD

**Issue by jvoigtlaender** [elm-lang/elm-lang.org#574]
Version 9.4.0 of highlight.js was released today. It has an updated syntax definition including the 0.17 changes surrounding module headers.

Do you want a PR with an upgrade of the highlight.js version used for highlighting code on http://elm-lang.org/?

**Comment by evancz** [comment]
Yeah, sounds good to me. Just try to keep it having the same set of languages.

**Comment by jvoigtlaender** [comment]
Actually, I just learnt it's a bit more complicated. The version of highlight.js currently used on the Elm sites is 8.8.0. The Elm 0.17 update came out with 9.4.0. Between the two appeared 9.0.0. And that 9.0.0 release changed how theme styles are written (which css classes are used etc.), in a backwards incompatible way, https://github.com/isagalaev/highlight.js/blob/master/CHANGES.md#version-900.

If the Elm sites were using some off-the shelf highlight.js theme, one could simply upgrade to an updated version of that theme along with the 9.4.0 update of highlight.js itself (updated themes are available from them). But for custom themes, it's more complicated. And it seems you have customized https://github.com/elm-lang/elm-lang.org/blob/master/resources/highlight/styles/default.css here.

So the options seem to be:

1. Update to version 9.4.0 of highlight.js, with Elm 0.17 syntax support, and select some off-the shelf theme from their collection.
2. Update to version 9.4.0 of highlight.js, with Elm 0.17 syntax support, and try to come up with a theme that exactly recreates how code looks on the current site. Maybe that's possible by choosing the current version of the off-the shelf theme that was also the basis for the Elm site's current custom theme, and trying to re-enact all the changes recorded in the commit history of https://github.com/elm-lang/elm-lang.org/commits/master/resources/highlight/styles/default.css. But it's nontrivial work.
3. Leave things as they are for now, and live without Elm 0.17 specific syntax highlighting.

Since there is no real pain felt at the moment about the lack of exact highlighting of Elm 0.17 module headers on the site(s), I guess 3. is what will happen.

Well, at least other users of highlight.js can now get Elm 0.17 specific highlighting, and as an added bonus, during the pull request to make the syntax definition upgrade happen there, the maintainer of highlight.js asked me whether I'd want an Elm example to be taken into the rotation of examples on the frontpage of https://highlightjs.org/. And that's reality now. :smile:

![screenshot](https://cloud.githubusercontent.com/assets/5853832/15338651/1db6f4f2-1c81-11e6-909c-30c691865884.png)

**Comment by sudhirvkumar** [comment]
@jvoigtlaender great work there :+1: Thanks

**Comment by evancz** [comment]
Cool about getting it listed on the website!

1 or 2 are the good options here, otherwise there's nothing to track. Original question is answered, so I'm going to close.
