### ISSUE TITLE
No instructions on how to get started with HTML examples on own machine?

### ISSUE THREAD

**Issue by lau** [elm-lang/elm-lang.org#575]
I found this command in a pull request (https://github.com/elm-lang/html/pull/12): `elm-package install -y elm-lang/html`

Where are new users supposed to find that command? There are a lot of examples that run in the in-browser-example-compile, but it is not easy to find out how to get them running on your own machine.

:)

**Comment by evancz** [comment]
Sorry you ran into this! A bunch of other folks did to, so with Elm 0.17, `elm-lang/html` is added to your dependencies by default, so you no longer have to run that command. Best way to document a tricky thing is to fix the tricky thing so it does not need docs anymore!
