### ISSUE TITLE
"Unable to find a set of packages .." installing elm-html with 0.17

### ISSUE THREAD

**Issue by jhw** [elm-lang/elm-lang.org#576]
Hi,

Having trouble running hello world HTML example from the command line having just upgraded to 0.17 on Ubuntu

----------------
# hello-world.elm

import Html exposing (span, text)
import Html.Attributes exposing (class)

main =
  span [class "welcome-message"] [text "Hello, World!"]

-----------------------------------

elm make hello-world.elm --output=index.html
Some new packages are needed. Here is the upgrade plan.

  Install:
    elm-lang/core 4.0.0

Do you approve of this plan? (y/n) y
Downloading elm-lang/core
Packages configured successfully!
I cannot find module 'Html'.

Module 'Main' is trying to import it.

Potential problems could be:
  * Misspelled the module name
  * Need to add a source directory or new dependency to elm-package.json
justin@justin-ThinkPad-X240:~/work/hello_world_elm$ elm package install evancz/elm-html
To install evancz/elm-html I would like to add the following
dependency to elm-package.json:

    "evancz/elm-html": "4.0.2 <= v < 5.0.0"

May I add that to elm-package.json for you? (y/n) y

Error: Unable to find a set of packages that will work with your constraints.

justin@justin-ThinkPad-X240:~/work/hello_world_elm$ 

:-(

Any thoughts ? Many thanks.

**Comment by evancz** [comment]
Run this:

```bash
elm-package install elm-lang/html
```

And you should be all set.

Also, please ask things like this on elm-discuss or on the slack channel or on IRC. Folks can help quicker there!

**Comment by jhw** [comment]
Thanks and apologies for trouble
