### ISSUE TITLE
404 on examples "use fewer parens" page

### ISSUE THREAD

**Issue by nini** [elm-lang/elm-lang.org#577]
http://elm-lang.org/examples/forward-apply is not reachable.

**Comment by princejwesley** [comment]
`forward-apply.elm` is [removed](https://github.com/elm-lang/elm-lang.org/commit/0366981b5b3493fb802686c02c5cca0311ce173f)

**Comment by nini** [comment]
So the link to it should also be removed? Or replaced with another content page?

**Comment by princejwesley** [comment]
####### Commit Message

"Remove a bunch of examples. Will add back piecemeal later."

**Comment by justgage** [comment]
I think it might be better in some cases to leave the page there with a message explaining that they've been removed. This seems more user friendly especially while we're still transitioning everything to 0.17 and there's a lot of blog posts around the Internet linking to them.

**Comment by evancz** [comment]
It looks like the link no longer exists. Sorry for the trouble!
