### ISSUE TITLE
Support for package elm-lang/lazy at /try

### ISSUE THREAD

**Issue by jvoigtlaender** [elm-lang/elm-lang.org#578]
People keep running into problems with recursive JSON decoding, and reporting those as issues on GitHub, e.g., https://github.com/elm-lang/core/issues/624.

To point out solutions to them, it would be really helpful if those solutions were runnable on http://elm-lang.org/try, but that requires package [elm-lang/lazy](http://package.elm-lang.org/packages/elm-lang/lazy) to be available there.

**Comment by evancz** [comment]
Don't need the lazy library for this AFIAK. Just use `andThen` with a thunk.

**Comment by jvoigtlaender** [comment]
Right, thanks for pointing that out. I gave a new answer over there that does not use `elm-lang/lazy`.
