### ISSUE TITLE
Record docs page broken

### ISSUE THREAD

**Issue by oakesja** [elm-lang/elm-lang.org#584]
When going to http://elm-lang.org/docs/records the page is blank and the following errors appear in the console: 

```
records:3840 Uncaught ReferenceError: _elm_lang$virtual_dom$VirtualDom$text is not defined(anonymous function) @ records:3840(anonymous function) @ records:4850
records:4852 Uncaught ReferenceError: Elm is not defined
```

This happens on both Google Chrome Version 51.0.2704.63 (64-bit) and Firefox 46.0.1

**Comment by evancz** [comment]
Should be fixed. Thanks for the report!
