### ISSUE TITLE
http://elm-lang.org/install is broken

### ISSUE THREAD

**Issue by plaxdan** [elm-lang/elm-lang.org#585]
> A web handler threw an exception. Details:
gen/pages/install.html: getFileStatus: does not exist (No such file or directory)

![image](https://cloud.githubusercontent.com/assets/382348/15830883/d088878e-2bd7-11e6-9e31-3d1843ed1ea2.png)

**Comment by evancz** [comment]
Is this still true?

The server is known to do this sometimes, but it appears to be very hard to reproduce.

**Comment by plaxdan** [comment]
Seems to be fixed now.
