### ISSUE TITLE
Farewell to FRP in Blog - Websocket not always working

### ISSUE THREAD

**Issue by pietro909** [elm-lang/elm-lang.org#587]
Hi there,
I was reading the blog post and I had an issue running the example.

The problem is that [here](https://github.com/elm-lang/elm-lang.org/blob/master/src/pages/blog/farewell-to-frp.elm#L150) you are using `ws://` protocol where sometimes (using proxies for instance) the secured one is required.

From Websocket.org:

> Note: In some environments the WebSocket connection may fail due to intermediary firewalls, proxies, routers, etc. In that case take advantage of WebSocket's secure capability and check Use secure WebSocket (TLS). Even if you have no issues you can still feel free to test using a secure connection. 

In should be simple to detect the failure and fall back to `wss://` I can't work on that now as I'm in the office.
Another solution would be just replace it and always use the secured one.

**Comment by evancz** [comment]
It is using wss now. Thanks for the report!
