### ISSUE TITLE
Hardware fault on Fedora 22

### ISSUE THREAD

**Issue by soycamo** [elm-lang/elm-lang.org#590]
When running the REPL, I have some strange behavior. If I type something in, it takes a while to actually do anything. Then if I Ctrl+C, I get an error from Elm.

Here's the terminal output:
```
11:42 me@compy ~ $ elm repl
---- elm repl 0.17.0 -----------------------------------------------------------
 :help for help, :exit to exit, more at <https://github.com/elm-lang/elm-repl>
--------------------------------------------------------------------------------
> 1 + 2

3 : number
> 
> 
> 
11:45 me@compy ~ $ elm repl
---- elm repl 0.17.0 -----------------------------------------------------------
 :help for help, :exit to exit, more at <https://github.com/elm-lang/elm-repl>
--------------------------------------------------------------------------------
> 
elm-repl: <stdin>: hGetChar: hardware fault (Input/output error)
```

**Comment by evancz** [comment]
Can you move this issue to https://github.com/elm-lang/elm-repl/issues

Thanks for the report! Any additional information about your platform, how you installed, etc. would help make progress on this. Like, what version of the OS? Do you have any special stuff installed or configured?
