### ISSUE TITLE
Confusing imports in examples

### ISSUE THREAD

**Issue by bhasto** [elm-lang/elm-lang.org#598]
I’ve been trying to go over the examples and I find one thing quite confusing.

http://guide.elm-lang.org/#a-quick-sample

```
import Html exposing (Html, button, div, text)
import Html.App as Html
```

After this I don’t understand what `Html` refers to. 

After some googling I think 3 things are in play: module `Html`, `Html` type in `Html` module and also `Html` alias for `Html.App` module. 

Have you considered not aliasing `Html.App` as `Html`?

**Comment by cobalamin** [comment]
I've also noticed this and always changed it to

```
import Html.App as App
```

**Comment by evancz** [comment]
I believe all the examples now use `import Html.App as App` to avoid this confusion. In addition, when Elm 0.18 comes out, `Html.App` merges into `Html`, further reducing the confusion around this.
