### ISSUE TITLE
Links to real life meetings

### ISSUE THREAD

**Issue by willnwhite** [elm-lang/elm-lang.org#604]
For instance, I'd like to start an Elm group in Nottingham, UK. Could there be a link in "Real Life" on the community page to meetings in cities (a separate page if necessary)? The section links to the SF Meetup page, but Meetup pages cost.

**Comment by evancz** [comment]
I believe this has been discussed already in #573 and #522. I think it is a good idea, but I also cannot own the maintenance of such a page. I think someone had an automated list, so follow up with them. If it's working, I'd love to add a link!

**Comment by willnwhite** [comment]
Sorry, I didn't think to search PRs too. Will search "This repository: Issues" (issues and PRs) from now on.

**Comment by evancz** [comment]
No worries! I'm not sure if @pootsbook is the right person to ping, but I'll add him anyway :)

**Comment by pootsbook** [comment]
@willnwhite I’ve got a list of meetup groups going here: https://www.elmlog.com/meetup_groups

At the moment it’s just pulling in from Meetup.com so if you have something outside of that let me know where I can get the details to pull them in ( poots on Elm Slack ).
