### ISSUE TITLE
Wrong lambda Calculation result 

### ISSUE THREAD

**Issue by djleonskennedy** [elm-lang/elm-lang.org#611]
**Hello**

Here is simple identity function that returns constant function

```
λ > (((lambda x.(lambda y.x))4)5)
α > (((λx.(λy.x))4)5)
β > ((λy.4)5)
β > 4
```

however when i try to represent it in elm i'm getting another result

```
((\x -> (\y -> x) 4) 5)
5 : number
```

_seems like i did mistake in some semantic stuff, could you clarify about lambda calculation rules in Elm? Thank you_

**Comment by cobalamin** [comment]
Not a bug. The expression behaves the same in Haskell :) You've made a semantic error with the parentheses.

Translating your Elm lambda expression back into your first lambda notation:

``` elm
((\x -> (\y -> x) 4) 5)
(( λx . (λy . x) 4) 5)
-- compare to original lambda (alignment with previous line intentional):
(((λx . (λy . x)) 4) 5)
```

Essentially what your Elm expression is defining is this function:

```elm
(\x -> (\y -> x) 4)
```

which takes any `x` and returns the immediate application of `(\y -> x)` to `4`, making `y := 4`, and it thus gets discarded, giving us `5`.

**Comment by djleonskennedy** [comment]
understood, thank you :)
