### ISSUE TITLE
Hints in Try editor are never loaded.

### ISSUE THREAD

**Issue by jhrcek** [elm-lang/elm-lang.org#616]
[Editor controls](https://github.com/elm-lang/elm-lang.org/blob/master/src/editor/EditorControls.elm) widget used in the [try editor](http://elm-lang.org/try) is supposed to be showing hints based on cursor position in the editor. However this feature is broken (no hints are ever displayed) and I see the following error in google chrome's js console:

```
XMLHttpRequest cannot load http://package.elm-lang.org/packages/elm-lang/core/latest/documentation.json. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://elm-lang.org' is therefore not allowed access.
```

I'm using Fedora 23, Google Chrome v 52.0.2743.82

**Comment by MatthiasWinkelmann** [comment]
This also completely breaks the WebSockets demo at http://elm-lang.org/examples/websockets.

**Comment by pietro909** [comment]
Hi @MatthiasWinkelmann for me the WebSocket demo is working, even if the error is present in console.

**Comment by MatthiasWinkelmann** [comment]
Thx @pietro909 – It's indeed working now. Maybe something else was amiss back then and I misinterpreted the error that was reported in the console.

**Comment by evancz** [comment]
I sorted this out for the 0.18 version of the website. Very excited to have this feature back!
