### ISSUE TITLE
Make install page more user friendly

### ISSUE THREAD

**Issue by qleonetti** [elm-lang/elm-lang.org#620]
Here's a few ideas:
* The npm install command could be directly visible without having to click.
* Not waiting for the "get started" page to explain (succinctly) what you are actually installing
* Having a clear path to learn Elm. There's a link to the get started page but it's not obvious. Maybe having it as the first sentence of the "Help" section, with a new title "Learn"

**Comment by evancz** [comment]
I think this has improved since the initial issue was opened. Are there things that can be better with the current version where "Get Started" is right on the home page and puts you directly into guide.elm-lang.org? If so, please start a new issue about that!
