### ISSUE TITLE
Add Maybe Maybe a -> Maybe a

### ISSUE THREAD

**Issue by iqualfragile** [elm-lang/elm-lang.org#621]
maybe call it crush or flatten or something.

**Comment by evancz** [comment]
I think it makes sense to suggest this to http://package.elm-lang.org/packages/elm-community/maybe-extra/1.1.0/

The idea is that a bunch of stuff like this lives in `*-extra` modules and we'll do a pass to bring the good stuff into core.

**Comment by iqualfragile** [comment]
is already in extra, called join
