### ISSUE TITLE
Referenced video lessons on Pragmatic Studios is no longer available

### ISSUE THREAD

**Issue by hakonrossebo** [elm-lang/elm-lang.org#623]
In http://elm-lang.org/get-started - Learning Elm - Continue learning, bullet point 2: the text is:

> If you prefer video tutorials, check out Pragmatics Studio's Elm tutorial: Elm: Building Reactive Web Apps with Mike Clark.

This page says:

> This course is no longer available as it is not compatible with the latest version of Elm (0.17). For the latest on Elm, we recommend An Introduction to Elm GitBook.

Maybe  link to some YouTube videos or [https://www.dailydrip.com/topics/elm](https://www.dailydrip.com/topics/elm)

**Comment by evancz** [comment]
I did a review of that page to improve things and got rid of the broken link. So this is resolved, but maybe not in the best way.
