### ISSUE TITLE
Style Guide Proposal: 2 Space Indentation

### ISSUE THREAD

**Issue by jehoshua02** [elm-lang/elm-lang.org#625]
Here we have what seems to be a neat, clean programming language, a shining hope in these dark days that sanity and programming might be able to frolic hand-in-hand into a bright, happy future. Unlike many languages, elm has an officially supported style guide. What a glorious accomplishment at such a young age. And yet ...

There is no word on indentation.

Poor elm-format is left on it's own to decide what to do. I propose a 2 space indentation.

Why?

+ __Adoption__. Judging by the many open source projects out there, many developers already have their editors configured for 2 space indentation for their css, javascript, and html. But whatever. I have other, more pragmatic reasons.
+ __Display Consistency__. I like my code to look the same no matter where it is displayed. Spaces are displayed consistently everywhere.
+ __Less Horizontal Scrolling__. Especially when running split screen, with test on one side and source on the other.
+ __Less is More__. Less indentation, means you have a few more characters, especially when indented several levels, before you run into the line-length limit and have to split that line of code in an awkward way.
+ __Easier to Read__. After having been on both sides of the religious battle, I find 2 spaces much easier to read than 4 spaces/tabs. Maybe it's because my eyes have less distance to travel or some other reason I'm unaware of. I'm really annoyed when my neat looking 2 space indented code gets blown away by elm-format, which I am compelled to use by well-meaning community members. I'll get over it if I have to, but I ❤️  2 space indentation.
+ __End The Battle__. Whether 2 spaces, 4 spaces, or tabs, I think it's important to end the battle, at least for the elm-community, as early as we can so we can move on with life.
+ __More Reasons__. It seems there are more logical reasons to go with 2 spaces than with 4 spaces or tabs. Tabs: fewer characters. 4 spaces: same as tabs, display consistency, but more characters. 2 spaces: all the reasons above plus this one.

If this is just going to be an unresolvable issue, close it. But maybe, just maybe, we can get 2 space indentation into the official style guide?

**Comment by evancz** [comment]
The elm-format folks had a bunch of discussion about this. The final choice of elm-format will be the final choice. I'll be reviewing the discussions they had, so that's the place to lobby for one thing or the other.

**Comment by jehoshua02** [comment]
@evancz Brilliant. Thank you.

**Comment by evancz** [comment]
Also, as someone with an 11 inch laptop, I am sympathetic to 2 spaces. I believe the deciding factor last time was that in "professional environments" where folks tend to have pretty big monitors, it is nice to do 4-space from the perspective of code texture and the resulting scanability. Gotta read back on the discussions though, I only heard about things 2nd hand.
