### ISSUE TITLE
Inconsistent statements in README concerning repo branches used

### ISSUE THREAD

**Issue by jvoigtlaender** [elm-lang/elm-lang.org#626]
It says there:
> ...  then running this script with `runhaskell BuildFromSource.hs 0.17`. Be aware that this is all the actively developed branches, ...

But actually `runhaskell BuildFromSource.hs 0.17` will build the `0.17` branches, which are not actively developed branches.

**Comment by evancz** [comment]
Can you just fix it? I don't know. The other guy said it was fine. Did not see you comment there.

**Comment by evancz** [comment]
Do a PR

**Comment by jvoigtlaender** [comment]
Don't know how you would want to see it fixed, since there are two possible ways (tell people to build `master` or not tell them they will have the actively developed branches). What other guy? Am only aware of discussion of the README of `elm-platform`, not this one here.

Point is: What is currently said in the README is factually wrong. A PR would need a decision made. I'm not the one to make that decision.

**Comment by evancz** [comment]
Can you link to the line in the github repo that needs to be changed? I don't know what you are talking about. Do a PR with the change you think is better.

**Comment by jvoigtlaender** [comment]
I'm talking about this line: https://github.com/elm-lang/elm-lang.org/blame/master/README.md#L10, which says that if one runs `runhaskell BuildFromSource.hs 0.17` one gets the actively developed branches of all the repositories.

I will make a PR with one of the two ways of fixing that.
