### ISSUE TITLE
Elm Online Editor indicates Error for  both Graphics.Element and Graphics.Collage Libraries 

### ISSUE THREAD

**Issue by kkruups** [elm-lang/elm-lang.org#629]
## Problem:

**_Same error below for both Graphics.Element & Graphics.Collage_**

**Error Message indicate in Elm Online Editor;**

```
I cannot find module 'Graphics.Element'.

Module 'Temp1473230001580255' is trying to import it.

Potential problems could be:
  * Misspelled the module name
  * Need to add a source directory or new dependency to elm-package.json

```

## Expected Behavior:
   
   Expected the code example from [gitbook: Elm Example Graphics API Page](https://csmith111.gitbooks.io/functional-reactive-programming-with-elm/content/section3/Graphics.html) to work.  There is even a link on the page to the Elm Online Editor.    

Request:
Please add a FAQ covering Online Editor Limitations/Restrictions.
If this reported issue is a bug please fix it accordingly.
(I searched for info on Elm Online Editor regarding Graphics API and could not find any info on the subject).

## Environment Info:

**OS:** Win 7 
**Browser;** Chrome Version 52.0.2743.116 m
**Elm Online Editor:** via both link on indicated in link above and going directly to http://elm-lang.org/try
**Elm:** 0.17,1

**Comment by kkruups** [comment]
This pretty old, any update on this issue

**Comment by evancz** [comment]
It appears that whatever book you are using has not been updated for 0.17, so it assumes the /try page works just like it did previous to that release.

At this time, the /try page has a couple packages available by default, but it doesn't have `elm-graphics`. You can use it from [here](http://package.elm-lang.org/packages/evancz/elm-graphics/latest) though.
