### ISSUE TITLE
Responsive mobile-friendly styles

### ISSUE THREAD

**Issue by elliotdickison** [elm-lang/elm-lang.org#634]
I would be willing to give this a shot if there is interest in a PR. GitBook is already fully responsive so the pages that still need some love are the homepage, the examples page, the community page, and the blog. I wouldn't plan to do anything with the online editor the first time around.

**Comment by evancz** [comment]
Go for it! This is one of the projects from https://github.com/elm-lang/projects/ and there's some explanation of how I think it should go.

**Comment by evancz** [comment]
I'd recommend doing one page at first. That way we can do a review and see if things are going in a good direction.
