### ISSUE TITLE
How do you include Ports?

### ISSUE THREAD

**Issue by tmcw** [elm-lang/elm-lang.org#635]
From: https://guide.elm-lang.org/interop/javascript.html

The documentation states:

> Assuming you know how to embed Elm in HTML, let's start with the JavaScript code we would add to react to messages coming through ports:

One way to read this would be that you should include your JavaScript with a `<script>` tag. I'm not sure if that's the actual right way, and what other possibility might be open. Ideally this documentation covers both the content of port and Elm code, but also where it goes and explicitly how it is included: using implication here is confusing.

**Comment by evancz** [comment]
Can you open this on https://github.com/evancz/guide.elm-lang.org/
