### ISSUE TITLE
"the Change function" in Text Fields doc

### ISSUE THREAD

**Issue by aaronkavlie-wf** [elm-lang/elm-lang.org#644]
This threw me off, in the [Text Fields](https://guide.elm-lang.org/architecture/user_input/text_fields.html) doc:

> This onInput function is kind of interesting. It takes one argument, in this case the Change function which was created when we declared the Msg type

How is `Change` a function? I'm pretty sure that's a mistake:

```elm
type Msg
  = Change String
```

The docs seem to have a hole here, as this construct only seems to be explained in the context of union types (I was looking for an explanation of types before getting into unions).

**Comment by OvermindDL1** [comment]
> How is `Change` a function? I'm pretty sure that's a mistake:

`Change "something"` is a value of the type of that union, but `Change` by itself is a function that takes a single string argument and returns a value of the type of that union.  They are just implicitly 'generated' by the language.  Maybe that should be stated in the docs somewhere in the union type section?

**Comment by evancz** [comment]
It is in the union type section. https://guide.elm-lang.org/types/union_types.html

Let's move discussions like this to the Elm slack or elm-discuss!

**Comment by rrodseth** [comment]
I just had the exact same question and found this issue after Googling "Elm Change function". The Union Types/Custom Types section comes later in the otherwise excellent tutorial.

**Comment by mrtnmgs** [comment]
same! I ended up here after googling "Elm Change" as I couldn't make sense of it at that point in the tutorial...

**Comment by yetkinozturk** [comment]
I have to say, same here... Thanks for the link though

**Comment by Monolitho** [comment]
Yes. I hope the doc can add a link to there. Love from 2024
