### ISSUE TITLE
[Guide] if example doesn't seem to work

### ISSUE THREAD

**Issue by bcardarella** [elm-lang/elm-lang.org#650]
Elm version: 0.17.1

The following is from the repl:

``` elm
> over9000 powerLevel = \
| if powerLevel > 9000 then "Its's over 9000!" else "meh"
-- SYNTAX PROBLEM -------------------------------------------- repl-temp-000.elm

I ran into something unexpected when parsing your code!

3|   over9000 powerLevel =
                         ^
I am looking for one of the following things:

    end of input
    whitespace
```

if I move the if onto the same line as the function definition the example works.

**Comment by iam-peekay** [comment]
@bcardarella the reason this happens is because you need to indent on the second line. 
```
> over9000 powerLevel = \
| [space][space] if powerLevel > 9000 then "Its's over 9000!" else "meh"

<function:_user$project$Repl$over9000> : number -> String
```

hope that helps!

**Comment by bcardarella** [comment]
Perhaps this is something that should be highlighted in the guides? I think the issue still makes sense to be addressed so it is not confusing. The resulting error message doesn't reveal the answer either. A mention that Elm expects significant whitespace would be helpful.

**Comment by iam-peekay** [comment]
@bcardarella great point! I agree. perhaps I'll make a PR to do this.

**Comment by evancz** [comment]
I know folks run into this a decent amount, but I am very unsure how or when to say that whitespace is important. It clearly is not clear, but I also do not know what to say about that.

**Comment by bcardarella** [comment]
@evancz for the example code it might help to show the invisibles

**Comment by bcardarella** [comment]
as far as when to say significant whitespace is required, I suspect it cannot be said early enough in the guides. Perhaps one of the very first things. Or even showing the first example and how it will fail if significant whitespace is not respected

**Comment by evancz** [comment]
Like I said, the hard part is turning this into a concrete change on [this page](https://github.com/evancz/guide.elm-lang.org/blob/master/core_language.md). If you want to give further suggestions, make a concrete proposal for that page. I understand the root problem, so saying suggestions disconnected from concrete actions is not valuable.

**Comment by bcardarella** [comment]
FWIW I just went through the guides again and ran into this exact same problem.
