### ISSUE TITLE
Global features for Elm application [unidirectional communication] [clarification]

### ISSUE THREAD

**Issue by djleonskennedy** [elm-lang/elm-lang.org#652]
Hi everyone,
I'm studying elm, and how I understood, it uses unidirectional communication, from parent to child.

But I cannot imagine any application which interact with an user and does not use notification messages (like http://codeseven.github.io/toastr/). In my opinion,  that messages implementation should be in separate module, let's call it 'Alert'. That module has message AddAlertMessage to add message to queue.

And then, I am implementing an authentication module let's call it 'Auth', and I do not understand how should I call message AddAlertMessage from Alert module to show error if it happen.

Then I read article (http://folkertdev.nl/blog/elm-child-parent-communication/) about using child to parent communication. And implement it with outmessage package. It works, but it look pretty ugly.

Also I generate a new message as a command " Task.perform identity identity (Task.succeed (AlertMsg <| Alert.Messages.AddAlertMessage Error "Error" msg)) ", it’s an anti-pattern.

Please Advice me how should I do that in proper (elm) way.

Thanks

**Comment by evancz** [comment]
It is best to ask questions like this on [elm-discuss](https://groups.google.com/forum/#!forum/elm-discuss) or on [the Elm slack channel](http://elmlang.herokuapp.com/). Folks are friendly and happy to help out!

Also, have you read https://guide.elm-lang.org in full? I think that's the best place to start before asking trickier questions like this. Often these questions have implicit assumptions (e.g. that parents and children exist in Elm programs) that are the root of the confusion.

**Comment by djleonskennedy** [comment]
Yes i've read https://guide.elm-lang.org in full? but it isn't solve this question at all

**Comment by evancz** [comment]
Okay, I'd recommend asking in either of the community forums mentioned above. Those are great places for questions like this because they can get you more specific feedback more quickly.

**Comment by djleonskennedy** [comment]
Ok seems like i'm still thinking in javascript, guess it's my problem for now, thank you
