### ISSUE TITLE
guide.elm-lang.org : can't see table of contents on the left

### ISSUE THREAD

**Issue by sneiderlein** [elm-lang/elm-lang.org#653]
**Chrome version: 54.0.2840.71 which is the latest stable**
I cannot see the table of contents in **guide.elm-lang.org**

**Chrome version 56.0.2906.0 canary**
Seems fine

am I doing something wrong?

**Comment by evancz** [comment]
No, it's not your fault. The book is hosted by gitbook.io so I suspect there's something weird in how they are rendering things. All I do is create markdown files and it's their job to show them correctly.

So not sure what is wrong, but it's neither your nor my fault :) Anyway, thanks for the heads up!
