### ISSUE TITLE
http demo is broken

### ISSUE THREAD

**Issue by maxgurewitz** [elm-lang/elm-lang.org#654]
The http demo is broken

http://elm-lang.org/examples/http

due to the fact that the constructed http request to retrieve gifs is malformed.  The http requst contains duplicates of some headers

```
access-control-allow-headers:Content-Type, Accept
access-control-allow-methods:GET, POST, PUT, DELETE, OPTIONS
access-control-allow-origin:*
access-control-allow-origin:*
age:0
age:0
```

**Comment by evancz** [comment]
I'm pretty sure this is a problem on giphy's side. The headers you show are **response** headers. I assume they will want to fix this pretty quickly, so I am going to close here.
