### ISSUE TITLE
How to embed elm-lang.org/try

### ISSUE THREAD

**Issue by teodorlu** [elm-lang/elm-lang.org#655]
Hello,

I'm writing a guide for learning Elm. To do this, I want to embed elm-lang.org/try with an iframe, using something like this:
```html
<iframe width="100%" height="300px" src="http://elm-lang.org/try"></iframe>
```

This kind of works, but the editable text area starts out really small:

![screenshot from 2016-11-01 21 04 05](https://cloud.githubusercontent.com/assets/5285452/19905380/caa4f82a-a076-11e6-921f-1b7d0b505b72.png)

The editable textarea may be dragget out to something larger, but I'd prefer having as much as possible "just work".

Any tips?

**Comment by evancz** [comment]
You are probably missing some CSS. I'd open up the developer console, go to the network tab, and see what things are not loading.

Also, is embedding it actually better than having an image? And that image links to the real thing.
