### ISSUE TITLE
http example broken

### ISSUE THREAD

**Issue by JoshTGreenwood** [elm-lang/elm-lang.org#657]
The http example is broken for me in Chrome Version 54.0.2840.71 (64-bit) on OSX 10.12.1 (16B2555).

![http 2016-11-01 21-41-07](https://cloud.githubusercontent.com/assets/1872899/19913809/31ebcd4c-a07c-11e6-83ae-832956a67c48.png)

**Comment by evancz** [comment]
Thanks for the report! The root problem is https://github.com/Giphy/GiphyAPI/issues/105, so it should be fixed soon.
