### ISSUE TITLE
Random bug in Get started/random?

### ISSUE THREAD

**Issue by rangzen** [elm-lang/elm-lang.org#659]
Hello,
in http://elm-lang.org/examples/random
change line 28 from
`(Model 1, Cmd.none)`
to
`(Model 1, Random.generate NewFace (Random.int 1 6))`
and Compile
The initialisation is random, you can roll and have new random numbers but if you compile again the initialisation will get you the same "random" number than the first compile.
Wait a bit and/or reload the page. Do the same and it will give you a new "random" initialisation but the behavior will stay the same : when you compile, you get the same initialisation value.

Is it a bug?

**Comment by evancz** [comment]
I'm not certain, but I suspect it has to do with the `Random` library. @mgold is working on an alternate implementation that will have better randomness properties, so I assume that'd be the fix. He can say more about this specific case, and if it's something else, we can bring that into the design process for the improved implementation.

**Comment by halfzebra** [comment]
@rangzen this is a bug, which is documented in [elm-lang/core/issues/724](https://github.com/elm-lang/core/issues/724)

In short, Random module from the core is not "random" enough.

For now you should use [mgold/elm-random-pcg](http://package.elm-lang.org/packages/mgold/elm-random-pcg/latest)

**Comment by rangzen** [comment]
Ok, thank you very much!
