### ISSUE TITLE
Invalid SSL cert on guide.elm-lang.org

### ISSUE THREAD

**Issue by bdougie** [elm-lang/elm-lang.org#660]
Anyone else seeing this on the elm guides? Maybe the cert has expired and needs a refresh?

I am have visited the guides on Chrome and Firebox and see this. I imagine not that big of a deal viewing the guides with broken SSL, but just want to make everyone aware, in case this is an easy fix with the hosting provider? I assume it's not GitHub pages...

<img width="444" alt="screenshot 2016-11-07 15 58 05" src="https://cloud.githubusercontent.com/assets/5713670/20083479/747c8612-a511-11e6-904f-c6338d706310.png">

**Comment by johnpmayer** [comment]
Must be a new chrome feature. Regardless, elm-lang.org is not served over
HTTPS

**Comment by bdougie** [comment]
Oh interesting, definitely not a big deal then. 💯

**Comment by OvermindDL1** [comment]
It appears it is served over https and http both, however the https cert is via github, so I'm guessing it is a github page hosted via a custom domain.  The recommended thing to do when that is the case is setup a redirect to redirect to the non-https version via javascript or so, it will not prevent the initial message but not much way of working around that without fully hosting it (which I can do if you want, static sites are utterly trivial to host and I have plenty of servers left).

However yes, Chrome, Firefox, and Edge have all announced they are going to try to enforce https in sites, kind of a built-in Https Everywhere plugin.  :-)

**Comment by evancz** [comment]
http://guide.elm-lang.org/ is hosted via github pages. Not sure how to fix that it serves through other means as well, and those other means have problems. I'm going to close this issue, and someone should open a new one on https://github.com/evancz/guide.elm-lang.org/ that refines it into a clearer description with suggestions about how to resolve it.
