### ISSUE TITLE
<title> arguments aren't user friendly

### ISSUE THREAD

**Issue by danfishgold** [elm-lang/elm-lang.org#664]
The `<title>`s for pages (most noticeable in the blog) aren't very user friendly:

* ["style-guide"](http://elm-lang.org/docs/style-guide) instead of "Style Guide",
* ["the-perfect-bug-report"](http://elm-lang.org/blog/the-perfect-bug-report) instead of "The Perfect Bug Report".

As far as I could see, [this line](https://github.com/elm-lang/elm-lang.org/blob/86c23d5b9bbbb57c8a02f72e9744d8dd47761748/src/backend/Generate.hs#L68) is the only one relevant.

**Comment by evancz** [comment]
They have been slightly improved by https://github.com/elm-lang/elm-lang.org/commit/94045261a39e82a21f2658efff2cffd1ef3d2fb3 which at least gets rid of the dashes. I am hesitant to do more based just on the file names though. Right now the server does not have a good mechanism for providing custom titles, so I think this is the best I can do for now.
