### ISSUE TITLE
Exception when loading homepage

### ISSUE THREAD

**Issue by patgoley** [elm-lang/elm-lang.org#668]
I received an error message when attempting to access elm-lang.org via mobile Safari. It read as follows:

A web handler threw and exception.
Details:
gen/pages/home.html: getFileStatus:
does not exist (No such file or directory)

After reloading the page, the homepage loaded correctly.

**Comment by patgoley** [comment]
This occurred on iOS 10.1.1.

**Comment by evancz** [comment]
This looks the same as https://github.com/elm-lang/elm-lang.org/issues/607 so let's follow along there. Root issue is the Haskell server doing something odd, and it seems to not be page specific.
