### ISSUE TITLE
Process Optimization

### ISSUE THREAD

**Issue by sils** [elm-lang/elm-lang.org#674]
Hi, I like that you have a bot.

We faced similar problem at coala.io and we already wrote a bot that does a bunch of things: you can use it at gitmate.io - it does autoresponds, automatic code review, and can help PR and issue organization. I really think you'd be better off if you'd use it (not only because you don't have to maintain an own bot but also because you can schedule your review times better, for coala we can use coala.io/review at all times to get all PRs over all projects that need review.)

Second: PR checklists like https://github.com/process-bot/contribution-checklist/blob/master/pulls.md#checklist are even better if you put them in the PR template: people see them before submitting a PR and they can actually check the boxes, maintainers can uncheck the boxes later. Also the checklist doesn't really match the purpose of this repo, this way you can customize it.

**Comment by evancz** [comment]
I like using @process-bot, but thank you for the suggestion!
