### ISSUE TITLE
Inconcistency between Debugger and the Navigation App

### ISSUE THREAD

**Issue by mickeyvip** [elm-lang/elm-lang.org#675]
I am not sure this is a real issue or if it can be addressed, but I wanted to point this out.

I have `navigation` application with several pages. Clicking on navigation link changes the browser's location and this causes the correct page to be shown.

I open the debugger and go back and forth application states.

While the pages are shown correctly, the browser's location is not affected and always stays the same.

Thank you.

**Comment by evancz** [comment]
The debugger cannot change anything when you go back into the past. It only lets you see old views.

A similar case would be if you have HTTP requests. The debugger does not resend them when you go back. Another case would be putting things in your database. The debugger does not redo that. Navigation is the same as these cases. It is an effect, meaning it is a change to state outside the Elm program. This category of changes are not safe to rerun on replay.
