### ISSUE TITLE
Record with 'interface' key produces undefined result when used with ports

### ISSUE THREAD

**Issue by vvanders** [elm-lang/elm-lang.org#677]
I have a port that looks like this:
```
port simplelink_init : { interface : String, callsign : String } -> Cmd msg
```

However when I use it like so:
```
case msg of
  InitAction(InitPage.SetLoopback) -> (Main(MainPage.init), simplelink_init { callsign = "KI7EST", loopback = "loopback"})
```

On the other end of the port the 'interface' key is undefined. It looks like the generated JS is adding an extra $:
```
case 'SetLoopback':
    return {
        ctor: '_Tuple2',
        _0: _user$project$Main$Main(_user$project$MainPage$init),
        _1: _user$project$Main$simplelink_init(
            {callsign: 'KI7EST', $interface: 'loopback'})
    }
```

If I change they key to 'foo':
```
port simplelink_init : { foo : String, callsign : String } -> Cmd msg
```

Then the generated JS looks correct and everything comes through fine:
```
case 'SetLoopback':
    return {
        ctor: '_Tuple2',
        _0: _user$project$Main$Main(_user$project$MainPage$init),
        _1: _user$project$Main$simplelink_init(
            {callsign: 'KI7EST', foo: 'loopback'})
    }
```

From what I could tell interface isn't a reserved keyword and the compiler didn't yell at me. This is elm version 0.18.0 and repo with repro branch is https://github.com/vvanders/simplelink/blob/elm_repro/ui/elm/Main.elm

Not sure if this is expected or not but it tripped me up so I thought I'd mention it here so someone else doesn't hit the same thing.

**Comment by adamdicarlo** [comment]
@vvanders I think this kind of issue is supposed to be filed at https://github.com/elm-lang/elm-compiler

**Comment by lukewestby** [comment]
agreed, please reopen on the compiler repo. thanks!

https://github.com/elm-lang/elm-compiler

**Comment by vvanders** [comment]
Got it, thanks for pointing me to the right repo, I'll go ahead and repost it there.
