### ISSUE TITLE
Missing Http Module

### ISSUE THREAD

**Issue by smorele** [elm-lang/elm-lang.org#683]
I've installed Elm 0.18 on my osX but I cannot compile [this official example](http://elm-lang.org/examples/http)
This it what my terminal returns:
```
elm-make Main.elm --output=index.html
I cannot find module 'Http'.

Module 'Main' is trying to import it.

Potential problems could be:
  * Misspelled the module name
  * Need to add a source directory or new dependency to elm-package.json
```

According to my researches, Http module is now included in Elm with [this repo](http://package.elm-lang.org/packages/elm-lang/http/latest)

**Comment by evancz** [comment]
You gotta run the following command to download it:

    elm-package install elm-lang/http
