### ISSUE TITLE
[Runtime Error] Function is not defined

### ISSUE THREAD

**Issue by beenotung** [elm-lang/elm-lang.org#706]
This is a compiler bug. It passes the complication but raise a runtime error.

## Error
```
Uncaught TypeError: f is not a function
    at Function.func (index.html:1495)
    at A2 (index.html:94)
    at Function.foldr [as func] (index.html:1222)
    at A3 (index.html:100)
    at index.html:1489
    at index.html:9
    at _beenotung$mindmap$MindMap_Chart$view (index.html:9431)
    at _beenotung$mindmap$MindMap_Container$view (index.html:9676)
    at _beenotung$mindmap$Main$view (index.html:9708)
    at updateIfNeeded (index.html:8565)
```

## Short
This will cause the error:
```
f = ... (using g)
g = ...
```
This will not cause the error:
```
g = ...
f = ... (using g)
```

## Detail

This will cause the error:
```
renderNodes : List Node -> List (Html Msg)
renderNodes =
    List.map renderNode


renderNode : Node -> Html Msg
renderNode node =
    case node of
        FreeMind.Decode.Node id name children ->
            Html.node "mindmap-node"
                []
                [ text name
                , div [] (renderNodes children)
                ]
```

This will not cause the error:
```
renderNode : Node -> Html Msg
renderNode node =
    case node of
        FreeMind.Decode.Node id name children ->
            Html.node "mindmap-node"
                []
                [ text name
                , div [] (renderNodes children)
                ]


renderNodes : List Node -> List (Html Msg)
renderNodes =
    List.map renderNode
```

## Meta Info
| | |
|-|-|
| Elm version | 0.18.0 |
| Browser | Google Chrome Version 56.0.2924.28 beta (64-bit) |
| OS | Arch Linux x86_64 |

## Project Repo
Just in case you want more detail https://github.com/beenotung/mindmap/blob/d114d95cb40fddd3a60682a62138222d174e3c2a/src/MindMap/Chart.elm#L38-L51

**Comment by evancz** [comment]
I think this is an example of https://github.com/elm-lang/elm-compiler/issues/1686, which will be resolved in the next release. If it persists in 0.19 please open an issue on the compiler repo about it. And thanks for the examples!
