### ISSUE TITLE
Typo on Maybe tutorial

### ISSUE THREAD

**Issue by tieTYT** [elm-lang/elm-lang.org#721]
On [this tutorial](https://guide.elm-lang.org/error_handling/maybe.html) there's a line that says

`if 13 <= age && age <= 18 then`

I think it should say this:

`if 13 >= age && age <= 18 then`

**Comment by lydell** [comment]
No, it's correct. Your version can actually be simplified to `age <= 13`, which does not do the same thing.

```
$ elm repl
> List.range 1 25 |> List.filter (\age -> 13 <= age && age <= 18)
[13,14,15,16,17,18] : List Int
> List.range 1 25 |> List.filter (\age -> 13 >= age && age <= 18)
[1,2,3,4,5,6,7,8,9,10,11,12,13] : List Int
> List.range 1 25 |> List.filter (\age -> age <= 13)
[1,2,3,4,5,6,7,8,9,10,11,12,13] : List Int
```
