### ISSUE TITLE
Type Classes

### ISSUE THREAD

**Issue by gleb-dianov** [elm-lang/elm-lang.org#726]
Hi, in 2012 you, @evancz, wrote that type classes are on your todo list. It's 2017, I just started learning Elm after having some fun time with Haskell and I want to throw it away and move to something like GHCjs every time I need to specify what kind of "map" I want. 

With this feature Elm definitely will be the best JavaScript replacement.

**Comment by evancz** [comment]
We try to use the issues for tracking bugs, so I am going to close. Thank you for the feedback. I recommend giving GHCJS a shot to see how you like it!
