### ISSUE TITLE
Add Documentation that `Native` is a "magical" name

### ISSUE THREAD

**Issue by adius** [elm-lang/elm-lang.org#727]
I wanted to restructure an elm app and moved some files from the Native directory to another directory. I assumed the name was given to the directory/module because the developer thought it was a good name for it. After hours of wondering why my code doesn't work and being annoyed by completely unhelpful compiler errors I figured it's because it has to be named `Native`. This isn't documented anywhere and was completely unobvious to me. A few more of such major fuck ups and I'm done with elm -.-

**Comment by rtfeldman** [comment]
> A few more of such major fuck ups and I'm done with elm

Please be civil.

**Comment by rtfeldman** [comment]
If you'd like to express your concern in a constructive way, please open another issue. See the `process-bot` comment above for guidelines on how to do this.

**Comment by adius** [comment]
Haha sorry, I guess a was a little upset after digging through the code for hours without any progress. 😅
