### ISSUE TITLE
Home page demo https://mantl.io/ is a broken link

### ISSUE THREAD

**Issue by tpoindex** [elm-lang/elm-lang.org#730]
Elm-lang.org home page demo link for  https://mantl.io/  is broken, appears that the server has vanished.  Cloudflare refreshes with an older page, but no demo.  Please remove and/or replace with another working demo.

**Comment by evancz** [comment]
@BrianHicks, can you make a PR that does that?

**Comment by BrianHicks** [comment]
yes, but it may be a couple of days.
