### ISSUE TITLE
The introduction and doc (guide.elm-lang.org)  does not print correctly

### ISSUE THREAD

**Issue by irathore** [elm-lang/elm-lang.org#731]
If we try to print the pages (or try to generate pdf by printing to pdf), only first page is rendered. It always creates only first page, no matter how long the doc is. All doc pages have this issue.

Tried firefox 54.0.1 and Chrome 59 (both on OSX 10.11.6)

Reproduce:

- go to http://guide.elm-lang.org
- Print the page, you will only get one page. Brows to next pages and will have same issue when trying to print it.

**Comment by evancz** [comment]
Try the "Download PDF" on this page https://www.gitbook.com/book/evancz/an-introduction-to-elm/details

Ask for help on Slack if you have further trouble!
