### ISSUE TITLE
Web site throwing exception and not loading: "getFileStatus: does not exist"

### ISSUE THREAD

**Issue by farolfo** [elm-lang/elm-lang.org#735]
SOMETIMES (NOT ALWAYS) after entering the website http://elm-lang.org/ I'm getting a blank page with the following two lines:
```
a web handler threw an exception. Details:
gen/pages/home.html: getFileStatus: does not exist (No such file or directory)
```

**Comment by evancz** [comment]
This is known. This issue does not give extra info to pin down the root cause though, so I don't think it makes sense to track it here.
