### ISSUE TITLE
Show how to use Elm for desktop applications

### ISSUE THREAD

**Issue by ShalokShalom** [elm-lang/elm-lang.org#738]
Hi there :smile: 

It is possible to use Elm to develop mobile and home applications for Android, iOS, macOS, Wayland, Windows, X.org and a bunch of others, with the same code.

They are inherently GPU accelerated and easy to code, can delight our eyes by smooth animations and scale to the used screen size automatically. 

The implementation is used by a huge community, available in an open source and closed source license, successfully used by thousands of developers and hundreds of companies.  

Code the logic with Elm, import your .js into [QML](https://doc.qt.io/qt-5/qmlapplications.html) and use it to develop the GUI super easy, in a JSON-like style. :smiley: 

You can run it in Qt Quick 2 and you can compile it thanks to the superb [Qt Quick Compiler](https://doc.qt.io/QtQuickCompiler/) into C++.

**Comment by evancz** [comment]
I don't think it makes sense to add documentation about this on the Elm website right now. Elm is focused on making web applications. That is what is officially supported. Other hacks may be possible, but I am not going to recommend things that are not officially supported.

**Comment by ShalokShalom** [comment]
I think you miss a great chance to make Elm popular and even more useful. 
Elm compiles into Javascript:
You can mark this as experimental, how you do it with much other stuff as well.
The community tests, grows and spend feedback. Where is the issue? 
Plus, you closed this issue, while i never wrote anything about putting it "right now" on the side.
Whats with the future? Why do you block the process so rigid as possible?
I thought you are different.

**Comment by ShalokShalom** [comment]
When I look on the huge list of open issues on the repos here, is help maybe appropriate.
A lot of people, including me, prefer declarative programming, and this is a declarative programming language, with less counterparts for the logic. Elm does not only support that, it even supports the whole range of Qt, while most other languages who are supported at all, can only use small parts of the ecosystem. Javascript is the main implementation in Qt, in addition to C++.

**Comment by ShalokShalom** [comment]
Elm compiles into Javascript:

You can mark this feature as experimental, so people get aware about it.
The community tests, intelligibles, grows, develops, plays and spend tons of helpful feedback. :smiley: 

A lot of people love declarative programming, and QML is an easy to use declarative language, which use JS for its invisible logic and Elm provides a great syntax to combine it. 

You might like to see, that JS supports the whole range of Qt, while most other languages who support Qt at all, can only use small parts of the ecosystem. So, QML is just the start. 

The whole ecosystem around Qt is huge. 

Javascript is the main implementation in Qt, in addition to C++. 
So using a transpiler to it, especially with such an awesome port system like in Elm is very smart.

When you are able to convert Elm language into Javascript, HTML, and CSS, you CAN port it to Qt with ease, believe me that. And think about it: How much easier becomes it, to write Elm code, without HTML, CSS, Virtual DOM and all this other software? It becomes a beginner language. 

Something, that gets told in schools. 

You might like to see that:
https://github.com/isRuslan/awesome-elm/pull/134#issuecomment-328324668
