### ISSUE TITLE
Elm won't install in `npm` v5

### ISSUE THREAD

**Issue by derekdreery** [elm-lang/elm-lang.org#743]
The new version of elm imposes some additional safety constraints on build scripts. You can work around this using `npm install -g elm --unsafe-perm=true --allow-root`, which bypasses the new checks. It would be helpful to have this on the website.

I'd submit a PR but my haskell version is 8 (arch linux), so I can't follow the build instructions.

**Comment by zwilias** [comment]
The recommended approach for npm permission issues is to [change its default installation location](https://docs.npmjs.com/getting-started/fixing-npm-permissions#option-2-change-npms-default-directory-to-another-directory). (By recommended, I mean this is what we recommend people do on Slack)

This is probably useful to add to the instructions.

**Comment by evancz** [comment]
Not sure any action to take here. Should this live on the `elm-platform` repo? Are there changes to make to this website? @zwilias can make a new issue in the right place if needed.
