### ISSUE TITLE
Add another lead maintainer

### ISSUE THREAD

**Issue by gDelgado14** [elm-lang/elm-lang.org#762]
I'd love to help out the elm project in whatever way possible. 

Perhaps I'm too new and / or unknown, but maybe we can have a well-known and respected community member help triage some of the issues in this repo. 

This frees up Evan a little bit to help him focus on bigger-picture work (such as the compiler / release for v0.19).

**Comment by evancz** [comment]
Things like this already exist. We don't have a "team" page at the moment though.

**Comment by evancz** [comment]
If you want to get involved, I recommend watching https://www.youtube.com/watch?v=DSjbTC-hvqQ from 2016
